	.align 2
gCryTable::
	cry Cry_Porygon
	cry Cry_Terapagos
	cry Cry_Cirno
	cry Cry_Rumia
	cry Cry_Koakuma
	cry Cry_Patchouli
	cry Cry_Remilia
	cry Cry_Flandre
	cry Cry_Letty
	cry Cry_AliceDoll
	cry Cry_Alice
	cry Cry_LilyWhite
	cry Cry_LilyBlack
	cry Cry_Youmu
	cry Cry_Reisen

	.align 2
gCryTable_Reverse::
	cry_reverse Cry_Porygon
	cry_reverse Cry_Terapagos
	cry_reverse Cry_Cirno
	cry_reverse Cry_Rumia
	cry_reverse Cry_Koakuma
	cry_reverse Cry_Patchouli
	cry_reverse Cry_Remilia
	cry_reverse Cry_Flandre
	cry_reverse Cry_Letty
	cry_reverse Cry_AliceDoll
	cry_reverse Cry_Alice
	cry_reverse Cry_LilyWhite
	cry_reverse Cry_LilyBlack
	cry_reverse Cry_Youmu
	cry_reverse Cry_Reisen
