	.align 2
DirectSoundWaveData_sc88pro_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88pro_glockenspiel.bin"

	.align 2
DirectSoundWaveData_sc88pro_organ2::
	.incbin "sound/direct_sound_samples/sc88pro_organ2.bin"

	.align 2
DirectSoundWaveData_sc88pro_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fretless_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_slap_bass::
	.incbin "sound/direct_sound_samples/sc88pro_slap_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_synth_bass::
	.incbin "sound/direct_sound_samples/sc88pro_synth_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani::
	.incbin "sound/direct_sound_samples/sc88pro_timpani.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/classical_choir_voice_ahhs.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.align 2
DirectSoundWaveData_unused_guitar_separates_power_chord::
	.incbin "sound/direct_sound_samples/unused_guitar_separates_power_chord.bin"

	.align 2
DirectSoundWaveData_unused_sc88pro_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88pro_unison_slap.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/unknown_snare.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_ohtsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_ohtsuzumi.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_hyoushigi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_hyoushigi.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_kick::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_kick.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_snare::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_tr909_hand_clap::
	.incbin "sound/direct_sound_samples/sc88pro_tr909_hand_clap.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_snare::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_snare.bin"

	.align 2
DirectSoundWaveData_unused_sc55_tom::
	.incbin "sound/direct_sound_samples/unused_sc55_tom.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/unknown_close_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_open_hihat::
	.incbin "sound/direct_sound_samples/unknown_open_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_bell::
	.incbin "sound/direct_sound_samples/unknown_bell.bin"

	.align 2
DirectSoundWaveData_sc88pro_tambourine::
	.incbin "sound/direct_sound_samples/sc88pro_tambourine.bin"

	.align 2
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "sound/direct_sound_samples/trinity_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_cymbal_crash::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_mute_high_conga::
	.incbin "sound/direct_sound_samples/sc88pro_mute_high_conga.bin"

	.align 2
DirectSoundWaveData_sc88pro_open_low_conga::
	.incbin "sound/direct_sound_samples/sc88pro_open_low_conga.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_kick.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/sd90_solo_snare.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/sd90_ambient_tom.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/dance_drums_ride_bell.bin"

	.align 2
DirectSoundWaveData_sd90_cowbell::
	.incbin "sound/direct_sound_samples/sd90_cowbell.bin"

	.align 2
DirectSoundWaveData_unused_heart_of_asia_indian_drum::
	.incbin "sound/direct_sound_samples/unused_heart_of_asia_indian_drum.bin"

	.align 2
DirectSoundWaveData_sd90_open_triangle::
	.incbin "sound/direct_sound_samples/sd90_open_triangle.bin"

	.align 2
DirectSoundWaveData_sc88pro_jingle_bell::
	.incbin "sound/direct_sound_samples/sc88pro_jingle_bell.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_atarigane::
	.incbin "sound/direct_sound_samples/ethnic_flavours_atarigane.bin"

	.align 2
DirectSoundWaveData_sc88pro_taiko::
	.incbin "sound/direct_sound_samples/sc88pro_taiko.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_kotsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_kotsuzumi.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_48::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_48.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_60::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_72::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_84::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_60::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_72::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_84::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_60::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_72::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_84::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_39:: @N.B.: These tuba samples are actually sampled at 36 and 48, then pitched up
	.incbin "sound/direct_sound_samples/sc88pro_tuba_39.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_51::
	.incbin "sound/direct_sound_samples/sc88pro_tuba_51.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_60::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_72::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_flute::
	.incbin "sound/direct_sound_samples/sc88pro_flute.bin"

	.align 2
DirectSoundWaveData_sc88pro_fingered_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fingered_bass.bin"

	.align 2
DirectSoundWaveData_unknown_koto_high::
	.incbin "sound/direct_sound_samples/unknown_koto_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "sound/direct_sound_samples/sd90_classical_shakuhachi.bin"

	.align 2
DirectSoundWaveData_unknown_koto_low::
	.incbin "sound/direct_sound_samples/unknown_koto_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.align 2
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "sound/direct_sound_samples/heart_of_asia_gamelan.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_low::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_low.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_high::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_high.bin"

	.align 2
DirectSoundWaveData_unknown_female_voice::
	.incbin "sound/direct_sound_samples/unknown_female_voice.bin"

	.align 2
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "sound/direct_sound_samples/unused_unknown_male_voice.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_high.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88pro_timpani_with_snare.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_square_wave::
	.incbin "sound/direct_sound_samples/sc88pro_square_wave.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.align 2
DirectSoundWaveData_unknown_1::
	.incbin "sound/direct_sound_samples/unknown_01.bin"

	.align 2
DirectSoundWaveData_sc88pro_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88pro_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_unknown_2::
	.incbin "sound/direct_sound_samples/unknown_02.bin"

	.align 2
DirectSoundWaveData_unknown_3::
	.incbin "sound/direct_sound_samples/unknown_03.bin"

	.align 2
DirectSoundWaveData_unknown_4::
	.incbin "sound/direct_sound_samples/unknown_04.bin"

	.align 2
DirectSoundWaveData_sc88pro_wind::
	.incbin "sound/direct_sound_samples/sc88pro_wind.bin"

	.align 2
DirectSoundWaveData_sc88pro_bubbles::
	.incbin "sound/direct_sound_samples/sc88pro_bubbles.bin"

	.align 2
DirectSoundWaveData_unknown_5::
	.incbin "sound/direct_sound_samples/unknown_05.bin"

	.align 2
DirectSoundWaveData_unknown_6::
	.incbin "sound/direct_sound_samples/unknown_06.bin"

	.align 2
DirectSoundWaveData_trinity_30303_mega_bass::
	.incbin "sound/direct_sound_samples/trinity_30303_mega_bass.bin"

	.align 2
DirectSoundWaveData_unknown_7::
	.incbin "sound/direct_sound_samples/unknown_07.bin"

	.align 2
DirectSoundWaveData_unknown_8::
	.incbin "sound/direct_sound_samples/unknown_08.bin"

	.align 2
DirectSoundWaveData_sc88pro_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88pro_tubular_bell.bin"

	.align 2
DirectSoundWaveData_unknown_9::
	.incbin "sound/direct_sound_samples/unknown_09.bin"

	.align 2
DirectSoundWaveData_trinity_big_boned::
	.incbin "sound/direct_sound_samples/trinity_big_boned.bin"

	.align 2
DirectSoundWaveData_sc88pro_harp::
	.incbin "sound/direct_sound_samples/sc88pro_harp.bin"

	.align 2
DirectSoundWaveData_sc88pro_xylophone::
	.incbin "sound/direct_sound_samples/sc88pro_xylophone.bin"

	.align 2
DirectSoundWaveData_unknown_10::
	.incbin "sound/direct_sound_samples/unknown_10.bin"

	.align 2
DirectSoundWaveData_unknown_11::
	.incbin "sound/direct_sound_samples/unknown_11.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion::
	.incbin "sound/direct_sound_samples/sc88pro_accordion.bin"

	.align 2
DirectSoundWaveData_unknown_12::
	.incbin "sound/direct_sound_samples/unknown_12.bin"

	.align 2
DirectSoundWaveData_unknown_13::
	.incbin "sound/direct_sound_samples/unknown_13.bin"

	.align 2
DirectSoundWaveData_unknown_14::
	.incbin "sound/direct_sound_samples/unknown_14.bin"

	.align 2
DirectSoundWaveData_unknown_15::
	.incbin "sound/direct_sound_samples/unknown_15.bin"

	.align 2
DirectSoundWaveData_unknown_16::
	.incbin "sound/direct_sound_samples/unknown_16.bin"

	.align 2
DirectSoundWaveData_unknown_17::
	.incbin "sound/direct_sound_samples/unknown_17.bin"

.if P_CRIES_ENABLED == TRUE
	.align 2
Cry_Porygon::
	.incbin "sound/direct_sound_samples/cries/porygon.bin"

	.align 2
Cry_Porygon2::
	.incbin "sound/direct_sound_samples/cries/porygon2.bin"

	.align 2
Cry_PorygonZ::
	.incbin "sound/direct_sound_samples/cries/porygon_z.bin"

	.align 2
Cry_Terapagos::
	.incbin "sound/direct_sound_samples/cries/terapagos.bin"

	.align 2
Cry_Reimu::
	.incbin "sound/direct_sound_samples/cries_add/reimu.bin"

	.align 2
Cry_Marisa::
	.incbin "sound/direct_sound_samples/cries_add/marisa.bin"

	.align 2
Cry_Daiyousei::
	.incbin "sound/direct_sound_samples/cries/daiyousei.bin"

	.align 2
Cry_Cirno::
	.incbin "sound/direct_sound_samples/cries/cirno.bin"

	.align 2
Cry_Rumia::
	.incbin "sound/direct_sound_samples/cries/rumia.bin"

	.align 2
Cry_Meiling::
	.incbin "sound/direct_sound_samples/cries/meiling.bin"

	.align 2
Cry_Koakuma::
	.incbin "sound/direct_sound_samples/cries/koakuma.bin"

	.align 2
Cry_Patchouli::
	.incbin "sound/direct_sound_samples/cries/patchouli.bin"

	.align 2
Cry_Sakuya::
	.incbin "sound/direct_sound_samples/cries/sakuya.bin"

	.align 2
Cry_Remilia::
	.incbin "sound/direct_sound_samples/cries/remilia.bin"

	.align 2
Cry_Flandre::
	.incbin "sound/direct_sound_samples/cries/flandre.bin"

	.align 2
Cry_Letty::
	.incbin "sound/direct_sound_samples/cries/letty.bin"

	.align 2
Cry_AliceDoll::
	.incbin "sound/direct_sound_samples/cries/alice_doll.bin"

	.align 2
Cry_Alice::
	.incbin "sound/direct_sound_samples/cries/alice.bin"

	.align 2
Cry_LilyWhite::
	.incbin "sound/direct_sound_samples/cries/lilywhite.bin"

	.align 2
Cry_LilyBlack::
	.incbin "sound/direct_sound_samples/cries/lilyblack.bin"

	.align 2
Cry_Lunasa::
	.incbin "sound/direct_sound_samples/cries_add/lunasa.bin"

	.align 2
Cry_Merlin::
	.incbin "sound/direct_sound_samples/cries_add/merlin.bin"

	.align 2
Cry_Lyrica::
	.incbin "sound/direct_sound_samples/cries_add/lyrica.bin"

	.align 2
Cry_Layla::
	.incbin "sound/direct_sound_samples/cries_add/layla.bin"

	.align 2
Cry_Youmu::
	.incbin "sound/direct_sound_samples/cries/youmu.bin"

	.align 2
Cry_Yuyuko::
	.incbin "sound/direct_sound_samples/cries_add/yuyuko.bin"

	.align 2
Cry_Chen::
	.incbin "sound/direct_sound_samples/cries/chen.bin"

	.align 2
Cry_Ran::
	.incbin "sound/direct_sound_samples/cries_add/ran.bin"

	.align 2
Cry_Yukari::
	.incbin "sound/direct_sound_samples/cries/yukari.bin"

	.align 2
Cry_Wriggle::
	.incbin "sound/direct_sound_samples/cries_add/wriggle.bin"

	.align 2
Cry_Mystia::
	.incbin "sound/direct_sound_samples/cries/mystia.bin"

	.align 2
Cry_Keine::
	.incbin "sound/direct_sound_samples/cries/keine.bin"

	.align 2
Cry_KeineBeast::
	.incbin "sound/direct_sound_samples/cries/keine_beast.bin"

	.align 2
Cry_Tewi::
	.incbin "sound/direct_sound_samples/cries_add/tewi.bin"

	.align 2
Cry_Reisen::
	.incbin "sound/direct_sound_samples/cries/reisen.bin"

	.align 2
Cry_ReisenII::
	.incbin "sound/direct_sound_samples/cries_add/reisen_ii.bin"

	.align 2
Cry_Eirin::
	.incbin "sound/direct_sound_samples/cries_add/eirin.bin"

	.align 2
Cry_Kaguya::
	.incbin "sound/direct_sound_samples/cries_add/kaguya.bin"

	.align 2
Cry_Mokou::
	.incbin "sound/direct_sound_samples/cries/mokou.bin"

	.align 2
Cry_Aya::
	.incbin "sound/direct_sound_samples/cries_add/aya.bin"

	.align 2
Cry_Medicine::
	.incbin "sound/direct_sound_samples/cries/medicine.bin"

	.align 2
Cry_Yuuka::
	.incbin "sound/direct_sound_samples/cries_add/yuuka.bin"

	.align 2
Cry_Komachi::
	.incbin "sound/direct_sound_samples/cries_add/komachi.bin"

	.align 2
Cry_Eiki::
	.incbin "sound/direct_sound_samples/cries_add/eiki.bin"

	.align 2
Cry_Shizuha::
	.incbin "sound/direct_sound_samples/cries/shizuha.bin"

	.align 2
Cry_Minoriko::
	.incbin "sound/direct_sound_samples/cries/minoriko.bin"

	.align 2
Cry_Hina::
	.incbin "sound/direct_sound_samples/cries_add/hina.bin"

	.align 2
Cry_Nitori::
	.incbin "sound/direct_sound_samples/cries_add/nitori.bin"

	.align 2
Cry_Momiji::
	.incbin "sound/direct_sound_samples/cries/momiji.bin"

	.align 2
Cry_Sanae::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Kanako::
	.incbin "sound/direct_sound_samples/cries_add/kanako.bin"

	.align 2
Cry_Suwako::
	.incbin "sound/direct_sound_samples/cries_add/suwako.bin"

	.align 2
Cry_Kisume::
	.incbin "sound/direct_sound_samples/cries_add/kisume.bin"

	.align 2
Cry_Yamame::
	.incbin "sound/direct_sound_samples/cries/yamame.bin"

	.align 2
Cry_Parsee::
	.incbin "sound/direct_sound_samples/cries_add/parsee.bin"

	.align 2
Cry_Yuugi::
	.incbin "sound/direct_sound_samples/cries/yuugi.bin"

	.align 2
Cry_Rin::
	.incbin "sound/direct_sound_samples/cries_add/rin.bin"

	.align 2
Cry_ZFairy::
	.incbin "sound/direct_sound_samples/cries_add/zombie_fairy.bin"

	.align 2
Cry_Utsuho::
	.incbin "sound/direct_sound_samples/cries_add/utsuho.bin"

	.align 2
Cry_Satori::
	.incbin "sound/direct_sound_samples/cries_add/satori.bin"

	.align 2
Cry_Koishi::
	.incbin "sound/direct_sound_samples/cries/koishi.bin"

	.align 2
Cry_Nazrin::
	.incbin "sound/direct_sound_samples/cries/nazrin.bin"

	.align 2
Cry_Kogasa::
	.incbin "sound/direct_sound_samples/cries_add/kogasa.bin"

	.align 2
Cry_Ichirin::
	.incbin "sound/direct_sound_samples/cries_add/ichirin.bin"

	.align 2
Cry_Murasa::
	.incbin "sound/direct_sound_samples/cries_add/murasa.bin"

	.align 2
Cry_Shou::
	.incbin "sound/direct_sound_samples/cries_add/shou.bin"

	.align 2
Cry_Byakuren::
	.incbin "sound/direct_sound_samples/cries_add/byakuren.bin"

	.align 2
Cry_Nue::
	.incbin "sound/direct_sound_samples/cries_add/nue.bin"

	.align 2
Cry_Kyouko::
	.incbin "sound/direct_sound_samples/cries_add/kyouko.bin"

	.align 2
Cry_Yoshika::
	.incbin "sound/direct_sound_samples/cries_add/yoshika.bin"

	.align 2
Cry_Seiga::
	.incbin "sound/direct_sound_samples/cries_add/seiga.bin"

	.align 2
Cry_Tojiko::
	.incbin "sound/direct_sound_samples/cries_add/tojiko.bin"

	.align 2
Cry_Futo::
	.incbin "sound/direct_sound_samples/cries_add/futo.bin"

	.align 2
Cry_Miko::
	.incbin "sound/direct_sound_samples/cries_add/miko.bin"

	.align 2
Cry_Mamizou::
	.incbin "sound/direct_sound_samples/cries_add/mamizou.bin"

	.align 2
Cry_Wakasagihime::
	.incbin "sound/direct_sound_samples/cries/wakasagihime.bin"

	.align 2
Cry_Suika::
	.incbin "sound/direct_sound_samples/cries/suika.bin"

	.align 2
Cry_Iku::
	.incbin "sound/direct_sound_samples/cries/iku.bin"

	.align 2
Cry_Tenshi::
	.incbin "sound/direct_sound_samples/cries_add/tenshi.bin"

	.align 2
Cry_Hatate::
	.incbin "sound/direct_sound_samples/cries/hatate.bin"

	.align 2
Cry_Sunny::
	.incbin "sound/direct_sound_samples/cries_add/sunny.bin"

	.align 2
Cry_Luna::
	.incbin "sound/direct_sound_samples/cries_add/luna.bin"

	.align 2
Cry_Star::
	.incbin "sound/direct_sound_samples/cries_add/star.bin"

	.align 2
Cry_Kokoro::
	.incbin "sound/direct_sound_samples/cries/kokoro.bin"

	.align 2
Cry_Kasen::
	.incbin "sound/direct_sound_samples/cries_add/kasen.bin"

	.align 2
Cry_Yorihime::
	.incbin "sound/direct_sound_samples/cries/yorihime.bin"

	.align 2
Cry_Toyohime::
	.incbin "sound/direct_sound_samples/cries_add/toyohime.bin"

	.align 2
Cry_Tokiko::
	.incbin "sound/direct_sound_samples/cries/tokiko.bin"

	.align 2
Cry_Kosuzu::
	.incbin "sound/direct_sound_samples/cries/kosuzu.bin"

	.align 2
Cry_Akyuu::
	.incbin "sound/direct_sound_samples/cries_add/akyuu.bin"

	.align 2
Cry_Rinnosuke::
	.incbin "sound/direct_sound_samples/cries_add/rinnosuke.bin"

	.align 2
Cry_Advent_Cirno::
	.incbin "sound/direct_sound_samples/cries_add/advent_cirno.bin"

	.align 2
Cry_Advent_Reisen::
	.incbin "sound/direct_sound_samples/cries_add/advent_reisen.bin"

	.align 2
Cry_Advent_Meiling::
	.incbin "sound/direct_sound_samples/cries_add/advent_meiling.bin"

	.align 2
Cry_Advent_Mystia::
	.incbin "sound/direct_sound_samples/cries_add/advent_mystia.bin"

	.align 2
Cry_Advent_Letty::
	.incbin "sound/direct_sound_samples/cries_add/advent_letty.bin"

	.align 2
Cry_Advent_Tewi::
	.incbin "sound/direct_sound_samples/cries_add/advent_tewi.bin"

	.align 2
Cry_Advent_Marisa::
	.incbin "sound/direct_sound_samples/cries/advent_marisa.bin"

	.align 2
Cry_Advent_Alice::
	.incbin "sound/direct_sound_samples/cries_add/advent_alice.bin"

	.align 2
Cry_Advent_Mokou::
	.incbin "sound/direct_sound_samples/cries_add/advent_mokou.bin"

	.align 2
Cry_Advent_Yukari::
	.incbin "sound/direct_sound_samples/cries_add/advent_yukari.bin"

	.align 2
Cry_Advent_Ran::
	.incbin "sound/direct_sound_samples/cries_add/advent_ran.bin"

	.align 2
Cry_Advent_Chen::
	.incbin "sound/direct_sound_samples/cries_add/advent_chen.bin"

	.align 2
Cry_Advent_Youmu::
	.incbin "sound/direct_sound_samples/cries_add/advent_youmu.bin"

	.align 2
Cry_Advent_Yuyuko::
	.incbin "sound/direct_sound_samples/cries_add/advent_yuyuko.bin"
.endif @ P_CRIES_ENABLED

	.align 2
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.align 2
DirectSoundWaveData_unknown_18::
	.incbin "sound/direct_sound_samples/unknown_18.bin"

	.align 2
DirectSoundWaveData_sc88pro_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88pro_nylon_str_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/sd90_special_scream_drive.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion_duplicate::
	.incbin "sound/direct_sound_samples/sc88pro_accordion_duplicate.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"

	.align 2
DirectSoundWaveData_touhou_death::
	.incbin "sound/direct_sound_samples/touhou_death.bin"

	.align 2
DirectSoundWaveData_prosamples_15_dance_drums_kick::
	.incbin "sound/direct_sound_samples/prosamples_15_dance_drums_kick.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_stick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_stick.bin"

	.align 2
DirectSoundWaveData_drill_dozer_bass_sample::
	.incbin "sound/direct_sound_samples/drill_dozer_bass_sample.bin"

	.align 2
DirectSoundWaveData_drill_dozer_trumpet_sample::
	.incbin "sound/direct_sound_samples/drill_dozer_trumpet_sample.bin"
