	.align 2
DirectSoundWaveData_sc88pro_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88pro_glockenspiel.bin"

	.align 2
DirectSoundWaveData_sc88pro_organ2::
	.incbin "sound/direct_sound_samples/sc88pro_organ2.bin"

	.align 2
DirectSoundWaveData_sc88pro_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fretless_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_slap_bass::
	.incbin "sound/direct_sound_samples/sc88pro_slap_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_synth_bass::
	.incbin "sound/direct_sound_samples/sc88pro_synth_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani::
	.incbin "sound/direct_sound_samples/sc88pro_timpani.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/classical_choir_voice_ahhs.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.align 2
DirectSoundWaveData_unused_guitar_separates_power_chord::
	.incbin "sound/direct_sound_samples/unused_guitar_separates_power_chord.bin"

	.align 2
DirectSoundWaveData_unused_sc88pro_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88pro_unison_slap.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/unknown_snare.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_ohtsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_ohtsuzumi.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_hyoushigi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_hyoushigi.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_kick::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_kick.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_snare::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_tr909_hand_clap::
	.incbin "sound/direct_sound_samples/sc88pro_tr909_hand_clap.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_snare::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_snare.bin"

	.align 2
DirectSoundWaveData_unused_sc55_tom::
	.incbin "sound/direct_sound_samples/unused_sc55_tom.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/unknown_close_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_open_hihat::
	.incbin "sound/direct_sound_samples/unknown_open_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_bell::
	.incbin "sound/direct_sound_samples/unknown_bell.bin"

	.align 2
DirectSoundWaveData_sc88pro_tambourine::
	.incbin "sound/direct_sound_samples/sc88pro_tambourine.bin"

	.align 2
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "sound/direct_sound_samples/trinity_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_cymbal_crash::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_mute_high_conga::
	.incbin "sound/direct_sound_samples/sc88pro_mute_high_conga.bin"

	.align 2
DirectSoundWaveData_sc88pro_open_low_conga::
	.incbin "sound/direct_sound_samples/sc88pro_open_low_conga.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_kick.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/sd90_solo_snare.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/sd90_ambient_tom.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/dance_drums_ride_bell.bin"

	.align 2
DirectSoundWaveData_sd90_cowbell::
	.incbin "sound/direct_sound_samples/sd90_cowbell.bin"

	.align 2
DirectSoundWaveData_unused_heart_of_asia_indian_drum::
	.incbin "sound/direct_sound_samples/unused_heart_of_asia_indian_drum.bin"

	.align 2
DirectSoundWaveData_sd90_open_triangle::
	.incbin "sound/direct_sound_samples/sd90_open_triangle.bin"

	.align 2
DirectSoundWaveData_sc88pro_jingle_bell::
	.incbin "sound/direct_sound_samples/sc88pro_jingle_bell.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_atarigane::
	.incbin "sound/direct_sound_samples/ethnic_flavours_atarigane.bin"

	.align 2
DirectSoundWaveData_sc88pro_taiko::
	.incbin "sound/direct_sound_samples/sc88pro_taiko.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_kotsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_kotsuzumi.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_48::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_48.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_60::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_72::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_84::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_60::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_72::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_84::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_60::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_72::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_84::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_39:: @N.B.: These tuba samples are actually sampled at 36 and 48, then pitched up
	.incbin "sound/direct_sound_samples/sc88pro_tuba_39.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_51::
	.incbin "sound/direct_sound_samples/sc88pro_tuba_51.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_60::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_72::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_flute::
	.incbin "sound/direct_sound_samples/sc88pro_flute.bin"

	.align 2
DirectSoundWaveData_sc88pro_fingered_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fingered_bass.bin"

	.align 2
DirectSoundWaveData_unknown_koto_high::
	.incbin "sound/direct_sound_samples/unknown_koto_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "sound/direct_sound_samples/sd90_classical_shakuhachi.bin"

	.align 2
DirectSoundWaveData_unknown_koto_low::
	.incbin "sound/direct_sound_samples/unknown_koto_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.align 2
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "sound/direct_sound_samples/heart_of_asia_gamelan.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_low::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_low.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_high::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_high.bin"

	.align 2
DirectSoundWaveData_unknown_female_voice::
	.incbin "sound/direct_sound_samples/unknown_female_voice.bin"

	.align 2
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "sound/direct_sound_samples/unused_unknown_male_voice.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_high.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88pro_timpani_with_snare.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_square_wave::
	.incbin "sound/direct_sound_samples/sc88pro_square_wave.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.align 2
DirectSoundWaveData_unknown_1::
	.incbin "sound/direct_sound_samples/unknown_01.bin"

	.align 2
DirectSoundWaveData_sc88pro_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88pro_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_unknown_2::
	.incbin "sound/direct_sound_samples/unknown_02.bin"

	.align 2
DirectSoundWaveData_unknown_3::
	.incbin "sound/direct_sound_samples/unknown_03.bin"

	.align 2
DirectSoundWaveData_unknown_4::
	.incbin "sound/direct_sound_samples/unknown_04.bin"

	.align 2
DirectSoundWaveData_sc88pro_wind::
	.incbin "sound/direct_sound_samples/sc88pro_wind.bin"

	.align 2
DirectSoundWaveData_sc88pro_bubbles::
	.incbin "sound/direct_sound_samples/sc88pro_bubbles.bin"

	.align 2
DirectSoundWaveData_unknown_5::
	.incbin "sound/direct_sound_samples/unknown_05.bin"

	.align 2
DirectSoundWaveData_unknown_6::
	.incbin "sound/direct_sound_samples/unknown_06.bin"

	.align 2
DirectSoundWaveData_trinity_30303_mega_bass::
	.incbin "sound/direct_sound_samples/trinity_30303_mega_bass.bin"

	.align 2
DirectSoundWaveData_unknown_7::
	.incbin "sound/direct_sound_samples/unknown_07.bin"

	.align 2
DirectSoundWaveData_unknown_8::
	.incbin "sound/direct_sound_samples/unknown_08.bin"

	.align 2
DirectSoundWaveData_sc88pro_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88pro_tubular_bell.bin"

	.align 2
DirectSoundWaveData_unknown_9::
	.incbin "sound/direct_sound_samples/unknown_09.bin"

	.align 2
DirectSoundWaveData_trinity_big_boned::
	.incbin "sound/direct_sound_samples/trinity_big_boned.bin"

	.align 2
DirectSoundWaveData_sc88pro_harp::
	.incbin "sound/direct_sound_samples/sc88pro_harp.bin"

	.align 2
DirectSoundWaveData_sc88pro_xylophone::
	.incbin "sound/direct_sound_samples/sc88pro_xylophone.bin"

	.align 2
DirectSoundWaveData_unknown_10::
	.incbin "sound/direct_sound_samples/unknown_10.bin"

	.align 2
DirectSoundWaveData_unknown_11::
	.incbin "sound/direct_sound_samples/unknown_11.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion::
	.incbin "sound/direct_sound_samples/sc88pro_accordion.bin"

	.align 2
DirectSoundWaveData_unknown_12::
	.incbin "sound/direct_sound_samples/unknown_12.bin"

	.align 2
DirectSoundWaveData_unknown_13::
	.incbin "sound/direct_sound_samples/unknown_13.bin"

	.align 2
DirectSoundWaveData_unknown_14::
	.incbin "sound/direct_sound_samples/unknown_14.bin"

	.align 2
DirectSoundWaveData_unknown_15::
	.incbin "sound/direct_sound_samples/unknown_15.bin"

	.align 2
DirectSoundWaveData_unknown_16::
	.incbin "sound/direct_sound_samples/unknown_16.bin"

	.align 2
DirectSoundWaveData_unknown_17::
	.incbin "sound/direct_sound_samples/unknown_17.bin"

.if P_CRIES_ENABLED == TRUE
	.align 2
Cry_Porygon::
	.incbin "sound/direct_sound_samples/cries/porygon.bin"

	.align 2
Cry_Porygon2::
	.incbin "sound/direct_sound_samples/cries/porygon2.bin"

	.align 2
Cry_PorygonZ::
	.incbin "sound/direct_sound_samples/cries/porygon_z.bin"

	.align 2
Cry_Terapagos::
	.incbin "sound/direct_sound_samples/cries/terapagos.bin"

	.align 2
Cry_Reimu::
	.incbin "sound/direct_sound_samples/cries/reimu.bin"

	.align 2
Cry_Marisa::
	.incbin "sound/direct_sound_samples/cries/marisa.bin"

	.align 2
Cry_Daiyousei::
	.incbin "sound/direct_sound_samples/cries/daiyousei.bin"

	.align 2
Cry_Cirno::
	.incbin "sound/direct_sound_samples/cries/cirno.bin"

	.align 2
Cry_Rumia::
	.incbin "sound/direct_sound_samples/cries/rumia.bin"

	.align 2
Cry_Meiling::
	.incbin "sound/direct_sound_samples/cries/meiling.bin"

	.align 2
Cry_Koakuma::
	.incbin "sound/direct_sound_samples/cries/koakuma.bin"

	.align 2
Cry_Patchouli::
	.incbin "sound/direct_sound_samples/cries/patchouli.bin"

	.align 2
Cry_Sakuya::
	.incbin "sound/direct_sound_samples/cries/sakuya.bin"

	.align 2
Cry_Remilia::
	.incbin "sound/direct_sound_samples/cries/remilia.bin"

	.align 2
Cry_Flandre::
	.incbin "sound/direct_sound_samples/cries/flandre.bin"

	.align 2
Cry_Letty::
	.incbin "sound/direct_sound_samples/cries/letty.bin"

	.align 2
Cry_AliceDoll::
	.incbin "sound/direct_sound_samples/cries/alice_doll.bin"

	.align 2
Cry_Alice::
	.incbin "sound/direct_sound_samples/cries/alice.bin"

	.align 2
Cry_LilyWhite::
	.incbin "sound/direct_sound_samples/cries/lilywhite.bin"

	.align 2
Cry_LilyBlack::
	.incbin "sound/direct_sound_samples/cries/lilyblack.bin"

	.align 2
Cry_Lunasa::
	.incbin "sound/direct_sound_samples/cries/lunasa.bin"

	.align 2
Cry_Merlin::
	.incbin "sound/direct_sound_samples/cries/merlin.bin"

	.align 2
Cry_Lyrica::
	.incbin "sound/direct_sound_samples/cries/lyrica.bin"

	.align 2
Cry_Layla::
	.incbin "sound/direct_sound_samples/cries/layla.bin"

	.align 2
Cry_Youmu::
	.incbin "sound/direct_sound_samples/cries/youmu.bin"

	.align 2
Cry_Yuyuko::
	.incbin "sound/direct_sound_samples/cries/yuyuko.bin"

	.align 2
Cry_Chen::
	.incbin "sound/direct_sound_samples/cries/chen.bin"

	.align 2
Cry_Ran::
	.incbin "sound/direct_sound_samples/cries/ran.bin"

	.align 2
Cry_Yukari::
	.incbin "sound/direct_sound_samples/cries/yukari.bin"

	.align 2
Cry_Wriggle::
	.incbin "sound/direct_sound_samples/cries/wriggle.bin"

	.align 2
Cry_Mystia::
	.incbin "sound/direct_sound_samples/cries/mystia.bin"

	.align 2
Cry_Keine::
	.incbin "sound/direct_sound_samples/cries/keine.bin"

	.align 2
Cry_KeineBeast::
	.incbin "sound/direct_sound_samples/cries/keine_beast.bin"

	.align 2
Cry_Tewi::
	.incbin "sound/direct_sound_samples/cries/tewi.bin"

	.align 2
Cry_Reisen::
	.incbin "sound/direct_sound_samples/cries/reisen.bin"

	.align 2
Cry_ReisenII::
	.incbin "sound/direct_sound_samples/cries/reisen_ii.bin"

	.align 2
Cry_Eirin::
	.incbin "sound/direct_sound_samples/cries/eirin.bin"

	.align 2
Cry_Kaguya::
	.incbin "sound/direct_sound_samples/cries/kaguya.bin"

	.align 2
Cry_Mokou::
	.incbin "sound/direct_sound_samples/cries/mokou.bin"

	.align 2
Cry_Aya::
	.incbin "sound/direct_sound_samples/cries/aya.bin"

	.align 2
Cry_Medicine::
	.incbin "sound/direct_sound_samples/cries/medicine.bin"

	.align 2
Cry_Yuuka::
	.incbin "sound/direct_sound_samples/cries/yuuka.bin"

	.align 2
Cry_Komachi::
	.incbin "sound/direct_sound_samples/cries/komachi.bin"

	.align 2
Cry_Eiki::
	.incbin "sound/direct_sound_samples/cries/eiki.bin"

	.align 2
Cry_Shizuha::
	.incbin "sound/direct_sound_samples/cries/shizuha.bin"

	.align 2
Cry_Minoriko::
	.incbin "sound/direct_sound_samples/cries/minoriko.bin"

	.align 2
Cry_Hina::
	.incbin "sound/direct_sound_samples/cries/hina.bin"

	.align 2
Cry_Nitori::
	.incbin "sound/direct_sound_samples/cries/nitori.bin"

	.align 2
Cry_Momiji::
	.incbin "sound/direct_sound_samples/cries/momiji.bin"

	.align 2
Cry_Sanae::
	.incbin "sound/direct_sound_samples/cries/sanae.bin"

	.align 2
Cry_Kanako::
	.incbin "sound/direct_sound_samples/cries/kanako.bin"

	.align 2
Cry_Suwako::
	.incbin "sound/direct_sound_samples/cries/suwako.bin"

	.align 2
Cry_Kisume::
	.incbin "sound/direct_sound_samples/cries/kisume.bin"

	.align 2
Cry_Yamame::
	.incbin "sound/direct_sound_samples/cries/yamame.bin"

	.align 2
Cry_Parsee::
	.incbin "sound/direct_sound_samples/cries/parsee.bin"

	.align 2
Cry_Yuugi::
	.incbin "sound/direct_sound_samples/cries/yuugi.bin"

	.align 2
Cry_Rin::
	.incbin "sound/direct_sound_samples/cries/rin.bin"

	.align 2
Cry_ZFairy::
	.incbin "sound/direct_sound_samples/cries/zombie_fairy.bin"

	.align 2
Cry_Utsuho::
	.incbin "sound/direct_sound_samples/cries/utsuho.bin"

	.align 2
Cry_Satori::
	.incbin "sound/direct_sound_samples/cries/satori.bin"

	.align 2
Cry_Koishi::
	.incbin "sound/direct_sound_samples/cries/koishi.bin"

	.align 2
Cry_Nazrin::
	.incbin "sound/direct_sound_samples/cries/nazrin.bin"

	.align 2
Cry_Kogasa::
	.incbin "sound/direct_sound_samples/cries/kogasa.bin"

	.align 2
Cry_Ichirin::
	.incbin "sound/direct_sound_samples/cries/ichirin.bin"

	.align 2
Cry_Murasa::
	.incbin "sound/direct_sound_samples/cries/murasa.bin"

	.align 2
Cry_Shou::
	.incbin "sound/direct_sound_samples/cries/shou.bin"

	.align 2
Cry_Byakuren::
	.incbin "sound/direct_sound_samples/cries/byakuren.bin"

	.align 2
Cry_Nue::
	.incbin "sound/direct_sound_samples/cries/nue.bin"

	.align 2
Cry_Kyouko::
	.incbin "sound/direct_sound_samples/cries/kyouko.bin"

	.align 2
Cry_Yoshika::
	.incbin "sound/direct_sound_samples/cries/yoshika.bin"

	.align 2
Cry_Seiga::
	.incbin "sound/direct_sound_samples/cries/seiga.bin"

	.align 2
Cry_Tojiko::
	.incbin "sound/direct_sound_samples/cries/tojiko.bin"

	.align 2
Cry_Futo::
	.incbin "sound/direct_sound_samples/cries/futo.bin"

	.align 2
Cry_Miko::
	.incbin "sound/direct_sound_samples/cries/miko.bin"

	.align 2
Cry_Mamizou::
	.incbin "sound/direct_sound_samples/cries/mamizou.bin"

	.align 2
Cry_Sekibanki::
	.incbin "sound/direct_sound_samples/cries/sekibanki.bin"

	.align 2
Cry_Kagerou::
	.incbin "sound/direct_sound_samples/cries/kagerou.bin"

	.align 2
Cry_Wakasagihime::
	.incbin "sound/direct_sound_samples/cries/wakasagihime.bin"

	.align 2
Cry_Benben::
	.incbin "sound/direct_sound_samples/cries/benben.bin"

	.align 2
Cry_Yatsuhashi::
	.incbin "sound/direct_sound_samples/cries/yatsuhashi.bin"

	.align 2
Cry_Raiko::
	.incbin "sound/direct_sound_samples/cries/raiko.bin"

	.align 2
Cry_Seija::
	.incbin "sound/direct_sound_samples/cries/seija.bin"

	.align 2
Cry_Shinmyoumaru::
	.incbin "sound/direct_sound_samples/cries/shinmyoumaru.bin"

	.align 2
Cry_Seiran::
	.incbin "sound/direct_sound_samples/cries/seiran.bin"

	.align 2
Cry_Ringo::
	.incbin "sound/direct_sound_samples/cries/ringo.bin"

	.align 2
Cry_Doremy::
	.incbin "sound/direct_sound_samples/cries/doremy.bin"

	.align 2
Cry_Sagume::
	.incbin "sound/direct_sound_samples/cries/sagume.bin"

	.align 2
Cry_Clownpiece::
	.incbin "sound/direct_sound_samples/cries/clownpiece.bin"

	.align 2
Cry_Junko::
	.incbin "sound/direct_sound_samples/cries/junko.bin"

	.align 2
Cry_Hecatia::
	.incbin "sound/direct_sound_samples/cries/hecatia.bin"

	.align 2
Cry_Eternity::
	.incbin "sound/direct_sound_samples/cries/eternity.bin"

	.align 2
Cry_Nemuno::
	.incbin "sound/direct_sound_samples/cries/nemuno.bin"

	.align 2
Cry_Aunn::
	.incbin "sound/direct_sound_samples/cries/aunn.bin"

	.align 2
Cry_Narumi::
	.incbin "sound/direct_sound_samples/cries/narumi.bin"

	.align 2
Cry_Teireida::
	.incbin "sound/direct_sound_samples/cries/teireida.bin"

	.align 2
Cry_Satono::
	.incbin "sound/direct_sound_samples/cries/satono.bin"

	.align 2
Cry_Okina::
	.incbin "sound/direct_sound_samples/cries/okina.bin"

	.align 2
Cry_Saki::
	.incbin "sound/direct_sound_samples/cries/saki.bin"

	.align 2
Cry_Takane::
	.incbin "sound/direct_sound_samples/cries/takane.bin"

	.align 2
Cry_Suika::
	.incbin "sound/direct_sound_samples/cries/suika.bin"

	.align 2
Cry_Iku::
	.incbin "sound/direct_sound_samples/cries/iku.bin"

	.align 2
Cry_Tenshi::
	.incbin "sound/direct_sound_samples/cries/tenshi.bin"

	.align 2
Cry_Hatate::
	.incbin "sound/direct_sound_samples/cries/hatate.bin"

	.align 2
Cry_Sunny::
	.incbin "sound/direct_sound_samples/cries/sunny.bin"

	.align 2
Cry_Luna::
	.incbin "sound/direct_sound_samples/cries/luna.bin"

	.align 2
Cry_Star::
	.incbin "sound/direct_sound_samples/cries/star.bin"

	.align 2
Cry_Kokoro::
	.incbin "sound/direct_sound_samples/cries/kokoro.bin"

	.align 2
Cry_Kasen::
	.incbin "sound/direct_sound_samples/cries/kasen.bin"

	.align 2
Cry_Yorihime::
	.incbin "sound/direct_sound_samples/cries/yorihime.bin"

	.align 2
Cry_Toyohime::
	.incbin "sound/direct_sound_samples/cries/toyohime.bin"

	.align 2
Cry_Tokiko::
	.incbin "sound/direct_sound_samples/cries/tokiko.bin"

	.align 2
Cry_Kosuzu::
	.incbin "sound/direct_sound_samples/cries/kosuzu.bin"

	.align 2
Cry_Hakurei::
	.incbin "sound/direct_sound_samples/cries/hakurei.bin"

	.align 2
Cry_Kirisame::
	.incbin "sound/direct_sound_samples/cries/kirisame.bin"

	.align 2
Cry_Genji::
	.incbin "sound/direct_sound_samples/cries/genji.bin"

	.align 2
Cry_Rika::
	.incbin "sound/direct_sound_samples/cries/rika.bin"

	.align 2
Cry_Meira::
	.incbin "sound/direct_sound_samples/cries/meira.bin"

	.align 2
Cry_Ellen::
	.incbin "sound/direct_sound_samples/cries/ellen.bin"

	.align 2
Cry_Kotohime::
	.incbin "sound/direct_sound_samples/cries/kotohime.bin"

	.align 2
Cry_Kana::
	.incbin "sound/direct_sound_samples/cries/kana.bin"

	.align 2
Cry_Rikako::
	.incbin "sound/direct_sound_samples/cries/rikako.bin"

	.align 2
Cry_Chiyuri::
	.incbin "sound/direct_sound_samples/cries/chiyuri.bin"

	.align 2
Cry_Yumemi::
	.incbin "sound/direct_sound_samples/cries/yumemi.bin"

	.align 2
Cry_Kedama::
	.incbin "sound/direct_sound_samples/cries/kedama.bin"

	.align 2
Cry_Ruukoto::
	.incbin "sound/direct_sound_samples/cries/ruukoto.bin"

	.align 2
Cry_Mimi_Chan::
	.incbin "sound/direct_sound_samples/cries/mimi_chan.bin"

	.align 2
Cry_Orange::
	.incbin "sound/direct_sound_samples/cries/orange.bin"

	.align 2
Cry_Kurumi::
	.incbin "sound/direct_sound_samples/cries/kurumi.bin"

	.align 2
Cry_Elly::
	.incbin "sound/direct_sound_samples/cries/elly.bin"

	.align 2
Cry_Kazami::
	.incbin "sound/direct_sound_samples/cries/kazami.bin"

	.align 2
Cry_Mugetsu::
	.incbin "sound/direct_sound_samples/cries/mugetsu.bin"

	.align 2
Cry_Gengetsu::
	.incbin "sound/direct_sound_samples/cries/gengetsu.bin"

	.align 2
Cry_Sara::
	.incbin "sound/direct_sound_samples/cries/sara.bin"

	.align 2
Cry_Louise::
	.incbin "sound/direct_sound_samples/cries/louise.bin"

	.align 2
Cry_Margatroid::
	.incbin "sound/direct_sound_samples/cries/margatroid.bin"

	.align 2
Cry_Yuki::
	.incbin "sound/direct_sound_samples/cries/yuki.bin"

	.align 2
Cry_Mai::
	.incbin "sound/direct_sound_samples/cries/mai.bin"

	.align 2
Cry_Yumeko::
	.incbin "sound/direct_sound_samples/cries/yumeko.bin"

	.align 2
Cry_Shinki::
	.incbin "sound/direct_sound_samples/cries/shinki.bin"

	.align 2
Cry_Akyuu::
	.incbin "sound/direct_sound_samples/cries/akyuu.bin"

	.align 2
Cry_Rinnosuke::
	.incbin "sound/direct_sound_samples/cries/rinnosuke.bin"

	.align 2
Cry_Tenma::
	.incbin "sound/direct_sound_samples/cries/tenma.bin"

	.align 2
Cry_Youki::
	.incbin "sound/direct_sound_samples/cries/youki.bin"

	.align 2
Cry_Tori::
	.incbin "sound/direct_sound_samples/cries/tori.bin"

	.align 2
Cry_Namazu::
	.incbin "sound/direct_sound_samples/cries/namazu.bin"

	.align 2
Cry_Tensoku::
	.incbin "sound/direct_sound_samples/cries/tensoku.bin"

	.align 2
Cry_Konngara::
	.incbin "sound/direct_sound_samples/cries/konngara.bin"

	.align 2
Cry_Kikuri::
	.incbin "sound/direct_sound_samples/cries/kikuri.bin"

	.align 2
Cry_Yuugenmagan::
	.incbin "sound/direct_sound_samples/cries/yuugenmagan.bin"

	.align 2
Cry_Sariel::
	.incbin "sound/direct_sound_samples/cries/sariel.bin"

	.align 2
Cry_Shingyoku::
	.incbin "sound/direct_sound_samples/cries/shingyoku.bin"

	.align 2
Cry_Elis::
	.incbin "sound/direct_sound_samples/cries/elis.bin"

	.align 2
Cry_Mima::
	.incbin "sound/direct_sound_samples/cries/mima.bin"

	.align 2
Cry_Sendai::
	.incbin "sound/direct_sound_samples/cries/sendai.bin"

	.align 2
Cry_Joshi_Kosei_Sanae::
	.incbin "sound/direct_sound_samples/cries/joshi_kosei_sanae.bin"

	.align 2
Cry_Dark_Alice::
	.incbin "sound/direct_sound_samples/cries/dark_alice.bin"

	.align 2
Cry_Aki_Sisters::
	.incbin "sound/direct_sound_samples/cries/aki_sisters.bin"

	.align 2
Cry_Advent_Cirno::
	.incbin "sound/direct_sound_samples/cries/advent_cirno.bin"

	.align 2
Cry_Advent_Reisen::
	.incbin "sound/direct_sound_samples/cries/advent_reisen.bin"

	.align 2
Cry_Advent_Meiling::
	.incbin "sound/direct_sound_samples/cries/advent_meiling.bin"

	.align 2
Cry_Advent_Mystia::
	.incbin "sound/direct_sound_samples/cries/advent_mystia.bin"

	.align 2
Cry_Advent_Letty::
	.incbin "sound/direct_sound_samples/cries/advent_letty.bin"

	.align 2
Cry_Advent_Tewi::
	.incbin "sound/direct_sound_samples/cries/advent_tewi.bin"

	.align 2
Cry_Advent_Marisa::
	.incbin "sound/direct_sound_samples/cries/advent_marisa.bin"

	.align 2
Cry_Advent_Alice::
	.incbin "sound/direct_sound_samples/cries/advent_alice.bin"

	.align 2
Cry_Advent_Mokou::
	.incbin "sound/direct_sound_samples/cries/advent_mokou.bin"

	.align 2
Cry_Advent_Yukari::
	.incbin "sound/direct_sound_samples/cries/advent_yukari.bin"

	.align 2
Cry_Advent_Ran::
	.incbin "sound/direct_sound_samples/cries/advent_ran.bin"

	.align 2
Cry_Advent_Chen::
	.incbin "sound/direct_sound_samples/cries/advent_chen.bin"

	.align 2
Cry_Advent_Youmu::
	.incbin "sound/direct_sound_samples/cries/advent_youmu.bin"

	.align 2
Cry_Advent_Yuyuko::
	.incbin "sound/direct_sound_samples/cries/advent_yuyuko.bin"

	.align 2
Cry_Petrified::
	.incbin "sound/direct_sound_samples/cries/petrified.bin"

	.align 2
Cry_Basiney::
	.incbin "sound/direct_sound_samples/cries/basiney.bin"

	.align 2
Cry_Blissea::
	.incbin "sound/direct_sound_samples/cries/blissea.bin"
.endif @ P_CRIES_ENABLED

	.align 2
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.align 2
DirectSoundWaveData_unknown_18::
	.incbin "sound/direct_sound_samples/unknown_18.bin"

	.align 2
DirectSoundWaveData_sc88pro_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88pro_nylon_str_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/sd90_special_scream_drive.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion_duplicate::
	.incbin "sound/direct_sound_samples/sc88pro_accordion_duplicate.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"

	.align 2
DirectSoundWaveData_touhou_death::
	.incbin "sound/direct_sound_samples/touhou_death.bin"

	.align 2
DirectSoundWaveData_prosamples_15_dance_drums_kick::
	.incbin "sound/direct_sound_samples/prosamples_15_dance_drums_kick.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_stick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_stick.bin"

	.align 2
DirectSoundWaveData_drill_dozer_bass_sample::
	.incbin "sound/direct_sound_samples/drill_dozer_bass_sample.bin"

	.align 2
DirectSoundWaveData_drill_dozer_trumpet_sample::
	.incbin "sound/direct_sound_samples/drill_dozer_trumpet_sample.bin"

	.align 2
DirectSoundWaveData_vs_wild_smol_sample::
	.incbin "sound/direct_sound_samples/unknown_add/vs_wild_smol_sample.bin"

	.align 2
Voice_OakIntro::
	.incbin "sound/direct_sound_samples/voice_lines/oak_intro.bin"

	.align 2
Voice_GigiLaugh::
	.incbin "sound/direct_sound_samples/voice_lines/uncomp_gigi_voice_laugh.bin"

	.align 2
Voice_GigiBoatGoesBinted::
	.incbin "sound/direct_sound_samples/voice_lines/uncomp_gigi_boat_goes_binted.bin"

	.align 2
DirectSoundWaveData_pinball_7_clav::
	.incbin "sound/direct_sound_samples/pinball_7_clav.bin"

	.align 2
DirectSoundWaveData_pinball_11_vibraphone::
	.incbin "sound/direct_sound_samples/pinball_11_vibraphone.bin"

	.align 2
DirectSoundWaveData_pinball_12_marimba::
	.incbin "sound/direct_sound_samples/pinball_12_marimba.bin"

	.align 2
DirectSoundWaveData_pinball_16_drawbar_organ::
	.incbin "sound/direct_sound_samples/pinball_16_drawbar_organ.bin"

	.align 2
DirectSoundWaveData_pinball_52_clarinet::
	.incbin "sound/direct_sound_samples/pinball_52_clarinet.bin"
