# 1 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"

# 2 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
LittlerootTown_MaysHouse_2F_MapScripts::
# 3 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	.byte 0
# 4 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"

# 5 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
LittlerootTown_MaysHouse_2F_EventScript_PC::
# 6 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	lockall
# 7 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	checkplayergender
# 8 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	msgbox gText_PokemonTrainerSchoolEmail, MSGBOX_DEFAULT
# 9 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	releaseall
# 10 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	end
