#ifndef GUARD_CONSTANTS_CRIES_H
#define GUARD_CONSTANTS_CRIES_H

enum {
    CRY_NONE,
    CRY_PORYGON,
    CRY_CIRNO,
    CRY_RUMIA,
    CRY_KOAKUMA,
    CRY_YOUMU,
    CRY_REISEN,
    CRY_COUNT,
};

#endif // GUARD_CONSTANTS_CRIES_H
