#ifndef GUARD_CONSTANTS_CRIES_H
#define GUARD_CONSTANTS_CRIES_H

enum {
    CRY_NONE,
    CRY_PORYGON,
    CRY_CIRNO,
    CRY_RUMIA,
    CRY_KOAKUMA,
    CRY_PATCHOULI,
    CRY_REMILIA,
    CRY_FLANDRE,
    CRY_LETTY,
    CRY_ALICE_DOLL,
    CRY_ALICE,
    CRY_LILY_WHITE,
    CRY_LILY_BLACK,
    CRY_YOUMU,
    CRY_REISEN,
    CRY_COUNT,
};

#endif // GUARD_CONSTANTS_CRIES_H
