#ifndef GUARD_CONSTANTS_CRIES_H
#define GUARD_CONSTANTS_CRIES_H

enum {
    CRY_NONE,
    CRY_PORYGON,
    CRY_TERAPAGOS,
    CRY_CIRNO,
    CRY_RUMIA,
    CRY_KOAKUMA,
    CRY_PATCHOULI,
    CRY_REMILIA,
    CRY_FLANDRE,
    CRY_LETTY,
    CRY_ALICE_DOLL,
    CRY_ALICE,
    CRY_LILY_WHITE,
    CRY_LILY_BLACK,
    CRY_YOUMU,
    CRY_CHEN,
    CRY_YUKARI,
    CRY_MYSTIA,
    CRY_KEINE,
    CRY_KEINE_BEAST,
    CRY_REISEN,
    CRY_MOKOU,
    CRY_MEDICINE,
    CRY_SHIZUHA,
    CRY_MINORIKO,
    CRY_MOMIJI,
    CRY_SANAE,
    CRY_COUNT,
};

#endif // GUARD_CONSTANTS_CRIES_H
