#ifndef GUARD_CONSTANTS_ITEMS_H
#define GUARD_CONSTANTS_ITEMS_H

#include "metaprogram.h"
#include "constants/tms_hms.h"

enum __attribute__((packed)) Item
{
    ITEM_NONE = 0,

    // Poké Balls
    ITEM_TOHO_ORB,
    ITEM_GREAT_ORB,
    ITEM_ULTRA_ORB,
    ITEM_MASTER_ORB,
    ITEM_PREMIER_ORB,
    ITEM_HEAL_ORB,
    ITEM_NET_ORB,
    ITEM_NEST_ORB,
    ITEM_DIVE_ORB,
    ITEM_DUSK_ORB,
    ITEM_TIMER_ORB,
    ITEM_QUICK_ORB,
    ITEM_REPEAT_ORB,
    ITEM_LUXURY_ORB,
    ITEM_LEVEL_BALL,
    ITEM_LURE_BALL,
    ITEM_MOON_BALL,
    ITEM_FRIEND_ORB,
    ITEM_LOVE_BALL,
    ITEM_FAST_BALL,
    ITEM_HEAVY_BALL,
    ITEM_DREAM_BALL,
    ITEM_SAFARI_ORB,
    ITEM_FOUL_ORB,
    ITEM_IGNITE_ORB,
    ITEM_BOMB_ORB,
    ITEM_PARK_BALL,
    ITEM_BEAST_BALL,
    ITEM_CHERISH_BALL,
    ITEM_POKE_BALL_HISUI,
    ITEM_GREAT_BALL_HISUI,
    ITEM_ULTRA_BALL_HISUI,
    ITEM_STRANGE_BALL,

    // Medicine
    ITEM_POTION,
    ITEM_SUPER_POTION,
    ITEM_HYPER_POTION,
    ITEM_MAX_POTION,
    ITEM_FULL_RESTORE,
    ITEM_REVIVE,
    ITEM_MAX_REVIVE,
    ITEM_FRESH_WATER,
    ITEM_SODA_POP,
    ITEM_LEMONADE,
    ITEM_MOOMOO_MILK,
    ITEM_ENERGY_POWDER,
    ITEM_ENERGY_ROOT,
    ITEM_HEAL_POWDER,
    ITEM_REVIVAL_HERB,
    ITEM_ANTIDOTE,
    ITEM_PARALYZE_HEAL,
    ITEM_BURN_HEAL,
    ITEM_ICE_HEAL,
    ITEM_AWAKENING,
    ITEM_FULL_HEAL,
    ITEM_ETHER,
    ITEM_MAX_ETHER,
    ITEM_ELIXIR,
    ITEM_MAX_ELIXIR,
    ITEM_BERRY_JUICE,
    ITEM_SACRED_ASH,
    ITEM_MAX_HONEY,

    // Regional Specialties
    ITEM_LAVA_COOKIE,
    ITEM_SCARLET_TEA,
    ITEM_GEYSER_WATER,
    ITEM_BEER_BOTTLE,
    ITEM_UNAGI_LUNCH,
    ITEM_SAKE_GOURD,
    ITEM_EIENTEI_POTION,
    ITEM_HEAVEN_PEACH,
    ITEM_REVIVAL_FLOWER,

    // Vitamins
    ITEM_HP_UP,
    ITEM_PROTEIN,
    ITEM_IRON,
    ITEM_CALCIUM,
    ITEM_ZINC,
    ITEM_CARBOS,
    ITEM_PP_UP,
    ITEM_PP_MAX,

    // EV Feathers
    ITEM_HEALTH_FEATHER,
    ITEM_MUSCLE_FEATHER,
    ITEM_RESIST_FEATHER,
    ITEM_GENIUS_FEATHER,
    ITEM_CLEVER_FEATHER,
    ITEM_SWIFT_FEATHER,

    // Mochi
    ITEM_HEALTH_MOCHI,
    ITEM_MUSCLE_MOCHI,
    ITEM_RESIST_MOCHI,
    ITEM_GENIUS_MOCHI,
    ITEM_CLEVER_MOCHI,
    ITEM_SWIFT_MOCHI,
    ITEM_FRESH_START_MOCHI,

    // Ability Modifiers
    ITEM_ABILITY_CAPSULE,
    ITEM_ABILITY_PATCH,

    // Mints
    ITEM_LONELY_MINT,
    ITEM_ADAMANT_MINT,
    ITEM_NAUGHTY_MINT,
    ITEM_BRAVE_MINT,
    ITEM_BOLD_MINT,
    ITEM_IMPISH_MINT,
    ITEM_LAX_MINT,
    ITEM_RELAXED_MINT,
    ITEM_MODEST_MINT,
    ITEM_MILD_MINT,
    ITEM_RASH_MINT,
    ITEM_QUIET_MINT,
    ITEM_CALM_MINT,
    ITEM_GENTLE_MINT,
    ITEM_CAREFUL_MINT,
    ITEM_SASSY_MINT,
    ITEM_TIMID_MINT,
    ITEM_HASTY_MINT,
    ITEM_JOLLY_MINT,
    ITEM_NAIVE_MINT,
    ITEM_SERIOUS_MINT,

    // Candy
    ITEM_RARE_CANDY,
    ITEM_EXP_CANDY_XS,
    ITEM_EXP_CANDY_S,
    ITEM_EXP_CANDY_M,
    ITEM_EXP_CANDY_L,
    ITEM_EXP_CANDY_XL,

    // Medicinal Flutes
    ITEM_BLUE_FLUTE,
    ITEM_YELLOW_FLUTE,
    ITEM_RED_FLUTE,

    // Encounter-modifying Flutes
    ITEM_BLACK_FLUTE,
    ITEM_WHITE_FLUTE,

    // Encounter Modifiers
    ITEM_REPEL,
    ITEM_SUPER_REPEL,
    ITEM_MAX_REPEL,
    ITEM_LURE,
    ITEM_SUPER_LURE,
    ITEM_MAX_LURE,

    ITEM_ESCAPE_ROPE,

    // X Items
    ITEM_X_ATTACK,
    ITEM_X_DEFENSE,
    ITEM_X_SP_ATK,
    ITEM_X_SP_DEF,
    ITEM_X_SPEED,
    ITEM_X_ACCURACY,

    ITEM_DIRE_HIT,
    ITEM_GUARD_SPEC,

    // Escape Items
    ITEM_POKE_DOLL,
    ITEM_FLUFFY_TAIL,
    ITEM_POKE_TOY,

    ITEM_MAX_MUSHROOMS,

    // Treasures
    ITEM_BOTTLE_CAP,
    ITEM_GOLD_BOTTLE_CAP,
    ITEM_NUGGET,
    ITEM_BIG_NUGGET,
    ITEM_GREEN_UFO,
    ITEM_RED_UFO,
    ITEM_BLUE_UFO,
    ITEM_PEARL,
    ITEM_BIG_PEARL,
    ITEM_PEARL_STRING,
    ITEM_STARDUST,
    ITEM_STAR_PIECE,
    ITEM_COMET_SHARD,
    ITEM_SHOAL_SALT,
    ITEM_SHOAL_SHELL,
    ITEM_RED_SHARD,
    ITEM_BLUE_SHARD,
    ITEM_YELLOW_SHARD,
    ITEM_GREEN_SHARD,
    ITEM_HEART_SCALE,
    ITEM_HONEY,
    ITEM_RARE_BONE,
    ITEM_ODD_KEYSTONE,
    ITEM_PRETTY_FEATHER,
    ITEM_RELIC_COPPER,
    ITEM_RELIC_SILVER,
    ITEM_RELIC_GOLD,
    ITEM_RELIC_VASE,
    ITEM_RELIC_BAND,
    ITEM_RELIC_STATUE,
    ITEM_RELIC_CROWN,
    ITEM_STRANGE_SOUVENIR,
    ITEM_BIG_BAMBOO_SHOOT,
    ITEM_TINY_BAMBOO_SHOOT,

    // Fossils
    ITEM_HELIX_FOSSIL,
    ITEM_DOME_FOSSIL,
    ITEM_OLD_AMBER,
    ITEM_ROOT_FOSSIL,

    // Mulch
    ITEM_GROWTH_MULCH,
    ITEM_DAMP_MULCH,
    ITEM_STABLE_MULCH,
    ITEM_GOOEY_MULCH,
    ITEM_RICH_MULCH,
    ITEM_SURPRISE_MULCH,
    ITEM_BOOST_MULCH,
    ITEM_AMAZE_MULCH,

    // Apricorns
    ITEM_RED_APRICORN,
    ITEM_BLUE_APRICORN,
    ITEM_YELLOW_APRICORN,
    ITEM_GREEN_APRICORN,
    ITEM_PINK_APRICORN,
    ITEM_WHITE_APRICORN,
    ITEM_BLACK_APRICORN,

    // Mail
    FIRST_MAIL_INDEX,
    ITEM_ORANGE_MAIL = FIRST_MAIL_INDEX,
    ITEM_HARBOR_MAIL,
    ITEM_GLITTER_MAIL,
    ITEM_MECH_MAIL,
    ITEM_WOOD_MAIL,
    ITEM_WAVE_MAIL,
    ITEM_BEAD_MAIL,
    ITEM_SHADOW_MAIL,
    ITEM_TROPIC_MAIL,
    ITEM_DREAM_MAIL,
    ITEM_FAB_MAIL,
    ITEM_RETRO_MAIL,

    // Evolution Items
    ITEM_POWER_HEART,
    ITEM_GUARD_HEART,
    ITEM_SWIFT_HEART,
    ITEM_TECH_HEART,
    ITEM_HELPER_HEART,
    ITEM_JUST_HEART,
    ITEM_CHROME_HEART,
    ITEM_NEUTRAL_HEART,
    ITEM_DUSK_STONE,
    ITEM_DAWN_STONE,
    ITEM_UPGRADE,
    ITEM_DUBIOUS_DISC,

    ITEM_EVERSTONE,

    // Tera Shards
    ITEM_BUG_TERA_SHARD,
    ITEM_DARK_TERA_SHARD,
    ITEM_DRAGON_TERA_SHARD,
    ITEM_ELECTRIC_TERA_SHARD,
    ITEM_FAIRY_TERA_SHARD,
    ITEM_FIGHTING_TERA_SHARD,
    ITEM_FIRE_TERA_SHARD,
    ITEM_FLYING_TERA_SHARD,
    ITEM_GHOST_TERA_SHARD,
    ITEM_GRASS_TERA_SHARD,
    ITEM_GROUND_TERA_SHARD,
    ITEM_ICE_TERA_SHARD,
    ITEM_NORMAL_TERA_SHARD,
    ITEM_POISON_TERA_SHARD,
    ITEM_PSYCHIC_TERA_SHARD,
    ITEM_ROCK_TERA_SHARD,
    ITEM_STEEL_TERA_SHARD,
    ITEM_WATER_TERA_SHARD,
    ITEM_STELLAR_TERA_SHARD,

    // Plates
    ITEM_FLAME_PLATE,
    ITEM_SPLASH_PLATE,
    ITEM_ZAP_PLATE,
    ITEM_MEADOW_PLATE,
    ITEM_ICICLE_PLATE,
    ITEM_FIST_PLATE,
    ITEM_TOXIC_PLATE,
    ITEM_EARTH_PLATE,
    ITEM_SKY_PLATE,
    ITEM_MIND_PLATE,
    ITEM_INSECT_PLATE,
    ITEM_STONE_PLATE,
    ITEM_SPOOKY_PLATE,
    ITEM_DRACO_PLATE,
    ITEM_DREAD_PLATE,
    ITEM_IRON_PLATE,
    ITEM_PIXIE_PLATE,

    // Colored Orbs
    ITEM_RED_ORB,
    ITEM_BLUE_ORB,

    // Gems
    ITEM_ILLUSION_CARD,
    ITEM_FIRE_CARD,
    ITEM_WATER_CARD,
    ITEM_WIND_CARD,
    ITEM_NATURE_CARD,
    ITEM_ICE_CARD,
    ITEM_DREAM_CARD,
    ITEM_MIASMA_CARD,
    ITEM_EARTH_CARD,
    ITEM_FLYING_GEM,
    ITEM_PSYCHIC_GEM,
    ITEM_BUG_GEM,
    ITEM_ROCK_GEM,
    ITEM_GHOST_GEM,
    ITEM_DRAGON_GEM,
    ITEM_DARK_GEM,
    ITEM_STEEL_GEM,
    ITEM_COSMIC_CARD,

    // Species-specific Held Items
    ITEM_ICY_BALL,
    ITEM_ASSIST_BALL,
    ITEM_MUSIC_BALL,
    ITEM_GLOW_BALL,
    ITEM_DARK_BALL,
    ITEM_BLOOMERS,
    ITEM_DARK_RIBBON,
    ITEM_BIG_CLOUD,
    ITEM_KUSANAGI,
    ITEM_YATA_MIRROR,
    ITEM_DOUBLE_SOUL,

    // Incenses
    ITEM_SEA_INCENSE,
    ITEM_LAX_INCENSE,
    ITEM_ODD_INCENSE,
    ITEM_ROCK_INCENSE,
    ITEM_FULL_INCENSE,
    ITEM_WAVE_INCENSE,
    ITEM_ROSE_INCENSE,
    ITEM_LUCK_INCENSE,
    ITEM_PURE_INCENSE,

    // EV Gain Modifiers
    ITEM_MACHO_BRACE,
    ITEM_POWER_WEIGHT,
    ITEM_POWER_BRACER,
    ITEM_POWER_BELT,
    ITEM_POWER_LENS,
    ITEM_POWER_BAND,
    ITEM_POWER_ANKLET,

    // Type-boosting Held Items
    ITEM_BRIDAL_GOWN,
    ITEM_WEDDING_DRESS = ITEM_BRIDAL_GOWN,
    ITEM_GOTHIC_DRESS,
    ITEM_GOTHIC_OUTFIT = ITEM_GOTHIC_DRESS,
    ITEM_SWIMSUIT,
    ITEM_NINJA_SUIT,
    ITEM_NINJA_COSTUME = ITEM_NINJA_SUIT,
    ITEM_CAMOUFLAGE,
    ITEM_THICK_FUR,
    ITEM_CHINESE_DRESS,
    ITEM_NURSE_UNIFORM,
    ITEM_GYM_SUIT,
    ITEM_SPORTS_SWEATER = ITEM_GYM_SUIT,
    ITEM_STEWARDESS,
    ITEM_AIRLINE_UNIFORM = ITEM_STEWARDESS,
    ITEM_WITCHS_ROBE,
    ITEM_WITCH_COSTUME = ITEM_WITCHS_ROBE,
    ITEM_BLAZER,
    ITEM_BUNNY_SUIT,
    ITEM_BUNNY_COSTUME = ITEM_BUNNY_SUIT,
    ITEM_BURIAL_DRESS,
    ITEM_PRIESTESS,
    ITEM_PRIEST_GARB = ITEM_PRIESTESS,
    ITEM_BLACK_GLASSES,
    ITEM_MISTRESS_OUTFIT = ITEM_BLACK_GLASSES,
    ITEM_MAID_UNIFORM,
    ITEM_FAIRY_FEATHER,

    // Alternate Type-boosting Held Items
    ITEM_SHARP_SWORD,
    ITEM_DUBIOUS_TOME,

    // Choice Items
    ITEM_CHOICE_RIBBON,
    ITEM_CHOICE_SPECS,
    ITEM_CHOICE_SCARF,

    // Status Orbs
    ITEM_FLAME_ORB,
    ITEM_TOXIC_ORB,
    ITEM_FROST_ORB,

    // Weather Rocks
    ITEM_DAMP_ROCK,
    ITEM_HEAT_ROCK,
    ITEM_SMOOTH_ROCK,
    ITEM_ICY_ROCK,
    ITEM_SCARLET_ROCK,

    // Terrain Seeds
    ITEM_ELECTRIC_SEED,
    ITEM_PSYCHIC_SEED,
    ITEM_MISTY_SEED,
    ITEM_GRASSY_SEED,

    // Type-activated Stat Modifiers
    ITEM_ABSORB_BULB,
    ITEM_CELL_BATTERY,
    ITEM_LUMINOUS_MOSS,
    ITEM_SNOWBALL,

    // Misc. Held Items
    ITEM_BRIGHT_POWDER,
    ITEM_WHITE_HERB,
    ITEM_EXP_SHARE,
    ITEM_EXP_ALL = ITEM_EXP_SHARE, // Gen I name
    ITEM_QUICK_CLAW,
    ITEM_SOOTHE_BELL,
    ITEM_MENTAL_HERB,
    ITEM_KINGS_ROCK,
    ITEM_DONATION_BOX,
    ITEM_CLEANSE_TAG,
    ITEM_SMOKE_BALL,
    ITEM_FOCUS_BAND,
    ITEM_LUCKY_EGG,
    ITEM_SCOPE_LENS,
    ITEM_BENTO_BOX,
    ITEM_SHELL_BELL,
    ITEM_WIDE_LENS,
    ITEM_MUSCLE_BAND,
    ITEM_WISE_GLASSES,
    ITEM_EXPERT_BELT,
    ITEM_LIGHT_CLAY,
    ITEM_LIFE_ORB,
    ITEM_POWER_HERB,
    ITEM_FOCUS_SASH,
    ITEM_ZOOM_LENS,
    ITEM_METRONOME,
    ITEM_IRON_BALL,
    ITEM_LAGGING_TAIL,
    ITEM_DESTINY_KNOT,
    ITEM_BLACK_SLUDGE,
    ITEM_GRIP_CLAW,
    ITEM_STICKY_BARB,
    ITEM_SHED_SHELL,
    ITEM_BIG_ROOT,
    ITEM_RAZOR_CLAW,
    ITEM_RAZOR_FANG,
    ITEM_EVIOLITE,
    ITEM_FLOAT_STONE,
    ITEM_ROCKY_HELMET,
    ITEM_AIR_BALLOON,
    ITEM_RED_CARD,
    ITEM_RING_TARGET,
    ITEM_BINDING_BAND,
    ITEM_EJECT_BUTTON,
    ITEM_WEAKNESS_POLICY,
    ITEM_ASSAULT_VEST,
    ITEM_SAFETY_GOGGLES,
    ITEM_ADRENALINE_ORB,
    ITEM_TERRAIN_EXTENDER,
    ITEM_PROTECTIVE_PADS,
    ITEM_THROAT_SPRAY,
    ITEM_EJECT_PACK,
    ITEM_HEAVY_DUTY_BOOTS,
    ITEM_BLUNDER_POLICY,
    ITEM_ROOM_SERVICE,
    ITEM_UTILITY_UMBRELLA,
    ITEM_ABILITY_SHIELD,
    ITEM_CLEAR_AMULET,
    ITEM_PUNCHING_GLOVE,
    ITEM_COVERT_CLOAK,
    ITEM_LOADED_DICE,
    ITEM_BOOSTER_ENERGY,
    ITEM_MIRROR_HERB,
    ITEM_BERSERK_GENE,

    // Berries
    FIRST_BERRY_INDEX,
    ITEM_CHERI_BERRY = FIRST_BERRY_INDEX,
    ITEM_CHESTO_BERRY,
    ITEM_PECHA_BERRY,
    ITEM_RAWST_BERRY,
    ITEM_ASPEAR_BERRY,
    ITEM_LEPPA_BERRY,
    ITEM_ORAN_BERRY,
    ITEM_PERSIM_BERRY,
    ITEM_LUM_BERRY,
    ITEM_SITRUS_BERRY,
    ITEM_FIGY_BERRY,
    ITEM_WIKI_BERRY,
    ITEM_MAGO_BERRY,
    ITEM_AGUAV_BERRY,
    ITEM_IAPAPA_BERRY,
    ITEM_RAZZ_BERRY,
    ITEM_BLUK_BERRY,
    ITEM_NANAB_BERRY,
    ITEM_WEPEAR_BERRY,
    ITEM_PINAP_BERRY,
    ITEM_POMEG_BERRY,
    ITEM_KELPSY_BERRY,
    ITEM_QUALOT_BERRY,
    ITEM_HONDEW_BERRY,
    ITEM_GREPA_BERRY,
    ITEM_TAMATO_BERRY,
    ITEM_CORNN_BERRY,
    ITEM_MAGOST_BERRY,
    ITEM_RABUTA_BERRY,
    ITEM_NOMEL_BERRY,
    ITEM_SPELON_BERRY,
    ITEM_PAMTRE_BERRY,
    ITEM_WATMEL_BERRY,
    ITEM_DURIN_BERRY,
    ITEM_BELUE_BERRY,
    ITEM_CHILAN_BERRY,
    ITEM_OCCA_BERRY,
    ITEM_PASSHO_BERRY,
    ITEM_WACAN_BERRY,
    ITEM_RINDO_BERRY,
    ITEM_YACHE_BERRY,
    ITEM_CHOPLE_BERRY,
    ITEM_KEBIA_BERRY,
    ITEM_SHUCA_BERRY,
    ITEM_COBA_BERRY,
    ITEM_PAYAPA_BERRY,
    ITEM_TANGA_BERRY,
    ITEM_CHARTI_BERRY,
    ITEM_KASIB_BERRY,
    ITEM_HABAN_BERRY,
    ITEM_COLBUR_BERRY,
    ITEM_BABIRI_BERRY,
    ITEM_ROSELI_BERRY,
    ITEM_LIECHI_BERRY,
    ITEM_GANLON_BERRY,
    ITEM_SALAC_BERRY,
    ITEM_PETAYA_BERRY,
    ITEM_APICOT_BERRY,
    ITEM_LANSAT_BERRY,
    ITEM_STARF_BERRY,
    ITEM_ENIGMA_BERRY,
    ITEM_MICLE_BERRY,
    ITEM_CUSTAP_BERRY,
    ITEM_JABOCA_BERRY,
    ITEM_ROWAP_BERRY,
    ITEM_KEE_BERRY,
    ITEM_MARANGA_BERRY,
    ITEM_PUMKIN_BERRY,
    ITEM_DRASH_BERRY,
    ITEM_EGGANT_BERRY,
    ITEM_STRIB_BERRY,
    ITEM_TURLAN_BERRY,
    ITEM_NUTPEA_BERRY,
    ITEM_IONNO_BERRY,
    ITEM_KUO_BERRY,
    ITEM_YAGO_BERRY,
    ITEM_TOUGA_BERRY,
    ITEM_GARLIG_BERRY,
    ITEM_TOPO_BERRY,
    LAST_BERRY_INDEX =  ITEM_TOPO_BERRY,

    // TMs/HMs
    ITEM_TM01,
    ITEM_TM02,
    ITEM_TM03,
    ITEM_TM04,
    ITEM_TM05,
    ITEM_TM06,
    ITEM_TM07,
    ITEM_TM08,
    ITEM_TM09,
    ITEM_TM10,
    ITEM_TM11,
    ITEM_TM12,
    ITEM_TM13,
    ITEM_TM14,
    ITEM_TM15,
    ITEM_TM16,
    ITEM_TM17,
    ITEM_TM18,
    ITEM_TM19,
    ITEM_TM20,
    ITEM_TM21,
    ITEM_TM22,
    ITEM_TM23,
    ITEM_TM24,
    ITEM_TM25,
    ITEM_TM26,
    ITEM_TM27,
    ITEM_TM28,
    ITEM_TM29,
    ITEM_TM30,
    ITEM_TM31,
    ITEM_TM32,
    ITEM_TM33,
    ITEM_TM34,
    ITEM_TM35,
    ITEM_TM36,
    ITEM_TM37,
    ITEM_TM38,
    ITEM_TM39,
    ITEM_TM40,
    ITEM_TM41,
    ITEM_TM42,
    ITEM_TM43,
    ITEM_TM44,
    ITEM_TM45,
    ITEM_TM46,
    ITEM_TM47,
    ITEM_TM48,
    ITEM_TM49,
    ITEM_TM50,
    ITEM_TM51,
    ITEM_TM52,
    ITEM_TM53,
    ITEM_TM54,
    ITEM_TM55,
    ITEM_TM56,
    ITEM_TM57,
    ITEM_TM58,
    ITEM_TM59,
    ITEM_TM60,
    ITEM_TM61,
    ITEM_TM62,
    ITEM_TM63,
    ITEM_TM64,
    ITEM_TM65,
    ITEM_TM66,
    ITEM_TM67,
    ITEM_TM68,
    ITEM_TM69,
    ITEM_TM70,
    ITEM_TM71,
    ITEM_TM72,
    ITEM_TM73,
    ITEM_TM74,
    ITEM_TM75,
    ITEM_TM76,
    ITEM_TM77,
    ITEM_TM78,
    ITEM_TM79,
    ITEM_TM80,
    ITEM_TM81,
    ITEM_TM82,
    ITEM_TM83,
    ITEM_TM84,
    ITEM_TM85,
    ITEM_TM86,
    ITEM_TM87,
    ITEM_TM88,
    ITEM_TM89,
    ITEM_TM90,
    ITEM_TM91,
    ITEM_TM92,
    ITEM_TM93,
    ITEM_TM94,
    ITEM_TM95,
    ITEM_TM96,
    ITEM_TM97,
    ITEM_TM98,
    ITEM_TM99,
    ITEM_TM100,

    ITEM_HM01,
    ITEM_HM02,
    ITEM_HM03,
    ITEM_HM04,
    ITEM_HM05,
    ITEM_HM06,
    ITEM_HM07,
    ITEM_HM08,


    /* Expands to:
     *   ITEM_TM_FOCUS_PUNCH = ITEM_TM01,
     *   ...
     *   ITEM_HM_CUT = ITM_HM01,
     *   ... */
    #define ENUM_TM(n, id) CAT(ITEM_TM_, id) = CAT(ITEM_TM, n),
    #define ENUM_HM(n, id) CAT(ITEM_HM_, id) = CAT(ITEM_HM, n),
    #define TO_TMHM_NUMS(a, ...) (__VA_ARGS__)
    RECURSIVELY(R_ZIP(ENUM_TM, TO_TMHM_NUMS NUMBERS_256, (FOREACH_TM(APPEND_COMMA))))
    RECURSIVELY(R_ZIP(ENUM_HM, TO_TMHM_NUMS NUMBERS_256, (FOREACH_HM(APPEND_COMMA))))
    #undef ENUM_TM
    #undef ENUM_HM
    #undef TO_TMHM_NUMS

    // Charms
    ITEM_OVAL_CHARM,
    ITEM_SHINY_CHARM,
    ITEM_CATCHING_CHARM,
    ITEM_EXP_CHARM,
    ITEM_GLIMMERING_CHARM,

    // Battle Mechanic Key Items
    ITEM_TERA_ORB,

    // Misc. Key Items
    ITEM_BICYCLE,
    ITEM_FISHING_ROD,
    ITEM_DOWSING_MACHINE,
    ITEM_ITEMFINDER = ITEM_DOWSING_MACHINE, // Pre-Gen IV name
    ITEM_DOWSING_MCHN = ITEM_DOWSING_MACHINE, // Gen IV-V name
    ITEM_TOWN_MAP,
    ITEM_VS_SEEKER,
    ITEM_TM_CASE,
    ITEM_BERRY_POUCH,
    ITEM_POKEMON_BOX_LINK,
    ITEM_POKEMON_BOX = ITEM_POKEMON_BOX_LINK, // Pre-Gen VIII name
    ITEM_COIN_CASE,
    ITEM_POWDER_JAR,
    ITEM_WAILMER_PAIL,
    ITEM_POKE_FLUTE,
    ITEM_FAME_CHECKER,
    ITEM_TOHOVIAL,
    ITEM_HEXORB,
    ITEM_OUTFIT_BOX,
    ITEM_MUSIC_PLAYER,

    // Story Key Items
    ITEM_BIG_AXE,
    ITEM_PAGER,
    ITEM_SURFBOARD,
    ITEM_POWER_GLOVE,
    ITEM_LANTERN,
    ITEM_PICKAXE,
    ITEM_CLIMBING_GEAR,
    ITEM_SCUBA_GEAR,

    // Story Key Items
    ITEM_SS_TICKET,
    ITEM_EON_TICKET,
    ITEM_MYSTIC_TICKET,
    ITEM_AURORA_TICKET,
    ITEM_OLD_SEA_MAP,
    ITEM_LETTER,
    ITEM_DEVON_PARTS,
    ITEM_DEVON_GOODS = ITEM_DEVON_PARTS, // Pre-Gen VI name
    ITEM_GO_GOGGLES,
    ITEM_DEVON_SCOPE,
    ITEM_BASEMENT_KEY,
    ITEM_SCANNER,
    ITEM_STORAGE_KEY,
    ITEM_KEY_TO_ROOM_1,
    ITEM_RM_1_KEY = ITEM_KEY_TO_ROOM_1, // Pre-Gen VI name
    ITEM_KEY_TO_ROOM_2,
    ITEM_RM_2_KEY = ITEM_KEY_TO_ROOM_2, // Pre-Gen VI name
    ITEM_KEY_TO_ROOM_4,
    ITEM_RM_4_KEY = ITEM_KEY_TO_ROOM_4, // Pre-Gen VI name
    ITEM_KEY_TO_ROOM_6,
    ITEM_RM_6_KEY = ITEM_KEY_TO_ROOM_6, // Pre-Gen VI name
    ITEM_METEORITE,
    ITEM_MAGMA_EMBLEM,
    ITEM_CONTEST_PASS,
    ITEM_PARCEL,
    ITEM_OAKS_PARCEL = ITEM_PARCEL, // Pre-Gen IV name
    ITEM_SECRET_KEY,
    ITEM_BIKE_VOUCHER,
    ITEM_GOLD_TEETH,
    ITEM_CARD_KEY,
    ITEM_LIFT_KEY,
    ITEM_SILPH_SCOPE,
    ITEM_TRI_PASS,
    ITEM_RAINBOW_PASS,
    ITEM_TEA,
    ITEM_RUBY,
    ITEM_SAPPHIRE,

    ITEM_TEACHY_TV,
    ITEM_POKE_RADAR,
    ITEM_POKEBLOCK_CASE,
    ITEM_MACH_BIKE,
    ITEM_ACRO_BIKE,
    ITEM_OLD_ROD,
    ITEM_GOOD_ROD,
    ITEM_SUPER_ROD,
    ITEM_SOOT_SACK,

    // Form-changing Key Items
    ITEM_ROTOM_CATALOG,

    ITEM_MEGA_RING,
    ITEM_Z_POWER_RING,
    ITEM_DYNAMAX_BAND,

    // Contest Scarves
    ITEM_RED_SCARF,
    ITEM_BLUE_SCARF,
    ITEM_PINK_SCARF,
    ITEM_GREEN_SCARF,
    ITEM_YELLOW_SCARF,

    // Z-Crystals
    ITEM_NORMALIUM_Z,
    ITEM_FIRIUM_Z,
    ITEM_WATERIUM_Z,
    ITEM_ELECTRIUM_Z,
    ITEM_GRASSIUM_Z,
    ITEM_ICIUM_Z,
    ITEM_FIGHTINIUM_Z,
    ITEM_POISONIUM_Z,
    ITEM_GROUNDIUM_Z,
    ITEM_FLYINIUM_Z,
    ITEM_PSYCHIUM_Z,
    ITEM_BUGINIUM_Z,
    ITEM_ROCKIUM_Z,
    ITEM_GHOSTIUM_Z,
    ITEM_DRAGONIUM_Z,
    ITEM_DARKINIUM_Z,
    ITEM_STEELIUM_Z,
    ITEM_FAIRIUM_Z,
    ITEM_INCINIUM_Z,
    ITEM_ULTRANECROZIUM_Z,

    ITEMS_COUNT,
    ITEM_FIELD_ARROW = ITEMS_COUNT,
};

// A special item id associated with "Cancel"/"Exit" etc. in a list of items or decorations
// Its icon is defined at ITEMS_COUNT as the "return to field" arrow
#define ITEM_LIST_END 0xFFFF

#if B_CONFUSE_BERRIES_HEAL >= GEN_8
    #define CONFUSE_BERRY_HEAL_FRACTION 3
#elif B_CONFUSE_BERRIES_HEAL == GEN_7
    #define CONFUSE_BERRY_HEAL_FRACTION 2
#else
    #define CONFUSE_BERRY_HEAL_FRACTION 8
#endif

#define CONFUSE_BERRY_HP_FRACTION ((B_CONFUSE_BERRIES_HEAL >= GEN_7) ? 4 : 2)

// Range of berries given out by various NPCS
#define FIRST_BERRY_MASTER_BERRY      ITEM_POMEG_BERRY
#define LAST_BERRY_MASTER_BERRY       ITEM_NOMEL_BERRY
#define FIRST_BERRY_MASTER_WIFE_BERRY ITEM_CHERI_BERRY
#define LAST_BERRY_MASTER_WIFE_BERRY  ITEM_SITRUS_BERRY
#define FIRST_KIRI_BERRY              ITEM_POMEG_BERRY
#define LAST_KIRI_BERRY               ITEM_NOMEL_BERRY
#define FIRST_ROUTE_114_MAN_BERRY     ITEM_RAZZ_BERRY
#define LAST_ROUTE_114_MAN_BERRY      ITEM_PINAP_BERRY

#define NUM_BERRY_MASTER_BERRIES          (LAST_BERRY_MASTER_BERRY - FIRST_BERRY_MASTER_BERRY + 1)
#define NUM_BERRY_MASTER_BERRIES_SKIPPED  (FIRST_BERRY_MASTER_BERRY - FIRST_BERRY_INDEX)
#define NUM_BERRY_MASTER_WIFE_BERRIES     (LAST_BERRY_MASTER_WIFE_BERRY - FIRST_BERRY_MASTER_WIFE_BERRY + 1)
#define NUM_KIRI_BERRIES                  (LAST_KIRI_BERRY - FIRST_KIRI_BERRY + 1)
#define NUM_KIRI_BERRIES_SKIPPED          (FIRST_KIRI_BERRY - FIRST_BERRY_INDEX)
#define NUM_ROUTE_114_MAN_BERRIES         (LAST_ROUTE_114_MAN_BERRY - FIRST_ROUTE_114_MAN_BERRY + 1)
#define NUM_ROUTE_114_MAN_BERRIES_SKIPPED (FIRST_ROUTE_114_MAN_BERRY - FIRST_BERRY_INDEX)

#define ITEM_TO_BERRY(itemId) (((itemId) - FIRST_BERRY_INDEX) + 1)
#define ITEM_TO_MAIL(itemId) ((itemId) - FIRST_MAIL_INDEX)
#define MAIL_NONE 0xFF
#define ITEM_TO_MULCH(itemId)(((itemId) - ITEM_GROWTH_MULCH) + 1)

#define MAX_BAG_ITEM_CAPACITY         999
#define MAX_PC_ITEM_CAPACITY          999
#define MAX_PYRAMID_BAG_ITEM_CAPACITY  99 // Values higher than 255 require free SaveBlock2 space.

#define MAX_ITEM_DIGITS         ((MAX_BAG_ITEM_CAPACITY > 99) ? 3 : 2)
#define MAX_PYRAMID_ITEM_DIGITS ((MAX_PYRAMID_BAG_ITEM_CAPACITY > 99) ? 3 : 2)

// Secondary IDs for rods
#define OLD_ROD   0
#define GOOD_ROD  1
#define SUPER_ROD 2

// Secondary IDs for bikes
#define MACH_BIKE 0
#define ACRO_BIKE 1

// Item parameters for EXP Candies
#define EXP_100   1
#define EXP_800   2
#define EXP_3000  3
#define EXP_10000 4
#define EXP_30000 5

// Item type IDs (used to determine the exit callback)
enum ItemType
{
    ITEM_USE_MAIL,
    ITEM_USE_PARTY_MENU,
    ITEM_USE_FIELD,
    ITEM_USE_PBLOCK_CASE,
    ITEM_USE_BAG_MENU, // No exit callback, stays in bag menu
    ITEM_USE_PARTY_MENU_MOVES,
    ITEM_USE_BATTLER, // Auto-select in Singles but lets you choose from party menu in Doubles
};

// Item battle script IDs (need to be non-zero)
enum EffectItem
{
    EFFECT_ITEM_ENIGMA_BERRY_EREADER = 1, // dummy constant
    EFFECT_ITEM_RESTORE_HP = 1, // needs to be non-zero
    EFFECT_ITEM_CURE_STATUS,
    EFFECT_ITEM_HEAL_AND_CURE_STATUS,
    EFFECT_ITEM_INCREASE_STAT,
    EFFECT_ITEM_SET_MIST,
    EFFECT_ITEM_SET_FOCUS_ENERGY,
    EFFECT_ITEM_ESCAPE,
    EFFECT_ITEM_THROW_BALL,
    EFFECT_ITEM_REVIVE,
    EFFECT_ITEM_RESTORE_PP,
    EFFECT_ITEM_INCREASE_ALL_STATS,
    EFFECT_ITEM_USE_POKE_FLUTE,
    EFFECT_ITEM_TAKE_DAMAGE,
};

#endif  // GUARD_CONSTANTS_ITEMS_H
