#ifndef GUARD_CONSTANTS_ITEMS_H
#define GUARD_CONSTANTS_ITEMS_H

#define ITEM_NONE 0

// Poké Balls
#define ITEM_TOHO_ORB 1
#define ITEM_GREAT_ORB 2
#define ITEM_ULTRA_ORB 3
#define ITEM_MASTER_ORB 4
#define ITEM_PREMIER_ORB 5
#define ITEM_FOUL_ORB 6
#define ITEM_NET_ORB 7
#define ITEM_NEST_ORB 8
#define ITEM_DIVE_ORB 9
#define ITEM_DUSK_ORB 10
#define ITEM_TIMER_ORB 11
#define ITEM_QUICK_ORB 12
#define ITEM_REPEAT_ORB 13
#define ITEM_LUXURY_ORB 14
#define ITEM_LEVEL_BALL 15
#define ITEM_LURE_BALL 16
#define ITEM_POKE_BALL_HISUI 17
#define ITEM_GREAT_BALL_HISUI 18
#define ITEM_ULTRA_BALL_HISUI 19
#define ITEM_FAST_BALL 20
#define ITEM_HEAVY_BALL 21
#define ITEM_DREAM_BALL 22
#define ITEM_SAFARI_ORB 23
#define ITEM_SPORT_BALL 24
#define ITEM_PARK_BALL 25
#define ITEM_BEAST_BALL 26
#define ITEM_CHERISH_BALL 27
#define ITEM_STRANGE_BALL 28

// Medicine
#define ITEM_POTION 29
#define ITEM_SUPER_POTION 30
#define ITEM_HYPER_POTION 31
#define ITEM_MAX_POTION 32
#define ITEM_FULL_RESTORE 33
#define ITEM_REVIVE 34
#define ITEM_MAX_REVIVE 35
#define ITEM_FRESH_WATER 36
#define ITEM_SODA_POP 37
#define ITEM_LEMONADE 38
#define ITEM_MOOMOO_MILK 39
#define ITEM_ENERGY_POWDER 40
#define ITEM_ENERGY_ROOT 41
#define ITEM_HEAL_POWDER 42
#define ITEM_REVIVAL_HERB 43
#define ITEM_ANTIDOTE 44
#define ITEM_PARALYZE_HEAL 45
#define ITEM_BURN_HEAL 46
#define ITEM_ICE_HEAL 47
#define ITEM_AWAKENING 48
#define ITEM_FULL_HEAL 49
#define ITEM_ETHER 50
#define ITEM_MAX_ETHER 51
#define ITEM_ELIXIR 52
#define ITEM_MAX_ELIXIR 53
#define ITEM_BERRY_JUICE 54
#define ITEM_SACRED_ASH 55
#define ITEM_MAX_HONEY 56

// Regional Specialties
#define ITEM_LAVA_COOKIE 57
#define ITEM_SCARLET_TEA 58
#define ITEM_GEYSER_WATER 59
#define ITEM_BEER_BOTTLE 60
#define ITEM_UNAGI_LUNCH 61
#define ITEM_SAKE_GOURD 62
#define ITEM_EIENTEI_POTION 63
#define ITEM_HEAVEN_PEACH 64
#define ITEM_REVIVAL_FLOWER 65

// Vitamins
#define ITEM_HP_UP 66
#define ITEM_PROTEIN 67
#define ITEM_IRON 68
#define ITEM_CALCIUM 69
#define ITEM_ZINC 70
#define ITEM_CARBOS 71
#define ITEM_PP_UP 72
#define ITEM_PP_MAX 73

// EV Feathers
#define ITEM_HEALTH_FEATHER 74
#define ITEM_HEALTH_WING ITEM_HEALTH_FEATHER // Pre-Gen VIII name
#define ITEM_MUSCLE_FEATHER 75
#define ITEM_MUSCLE_WING ITEM_MUSCLE_FEATHER // Pre-Gen VIII name
#define ITEM_RESIST_FEATHER 76
#define ITEM_RESIST_WING ITEM_RESIST_FEATHER // Pre-Gen VIII name
#define ITEM_GENIUS_FEATHER 77
#define ITEM_GENIUS_WING ITEM_GENIUS_FEATHER // Pre-Gen VIII name
#define ITEM_CLEVER_FEATHER 78
#define ITEM_CLEVER_WING ITEM_CLEVER_FEATHER // Pre-Gen VIII name
#define ITEM_SWIFT_FEATHER 79
#define ITEM_SWIFT_WING ITEM_SWIFT_FEATHER // Pre-Gen VIII name

// Mochi
#define ITEM_HEALTH_MOCHI 80
#define ITEM_MUSCLE_MOCHI 81
#define ITEM_RESIST_MOCHI 82
#define ITEM_GENIUS_MOCHI 83
#define ITEM_CLEVER_MOCHI 84
#define ITEM_SWIFT_MOCHI 85
#define ITEM_FRESH_START_MOCHI 86

// Ability Modifiers
#define ITEM_ABILITY_CAPSULE 87
#define ITEM_ABILITY_PATCH 88

// Mints
#define ITEM_LONELY_MINT 89
#define ITEM_ADAMANT_MINT 90
#define ITEM_NAUGHTY_MINT 91
#define ITEM_BRAVE_MINT 92
#define ITEM_BOLD_MINT 93
#define ITEM_IMPISH_MINT 94
#define ITEM_LAX_MINT 95
#define ITEM_RELAXED_MINT 96
#define ITEM_MODEST_MINT 97
#define ITEM_MILD_MINT 98
#define ITEM_RASH_MINT 99
#define ITEM_QUIET_MINT 100
#define ITEM_CALM_MINT 101
#define ITEM_GENTLE_MINT 102
#define ITEM_CAREFUL_MINT 103
#define ITEM_SASSY_MINT 104
#define ITEM_TIMID_MINT 105
#define ITEM_HASTY_MINT 106
#define ITEM_JOLLY_MINT 107
#define ITEM_NAIVE_MINT 108
#define ITEM_SERIOUS_MINT 109

// Candy
#define ITEM_RARE_CANDY 110
#define ITEM_EXP_CANDY_XS 111
#define ITEM_EXP_CANDY_S 112
#define ITEM_EXP_CANDY_M 113
#define ITEM_EXP_CANDY_L 114
#define ITEM_EXP_CANDY_XL 115
#define ITEM_DYNAMAX_CANDY 116

// Medicinal Flutes
#define ITEM_BLUE_FLUTE 117
#define ITEM_YELLOW_FLUTE 118
#define ITEM_RED_FLUTE 119

// Encounter-modifying Flutes
#define ITEM_BLACK_FLUTE 120
#define ITEM_WHITE_FLUTE 121

// Encounter Modifiers
#define ITEM_REPEL 122
#define ITEM_SUPER_REPEL 123
#define ITEM_MAX_REPEL 124
#define ITEM_LURE 125
#define ITEM_SUPER_LURE 126
#define ITEM_MAX_LURE 127

#define ITEM_ESCAPE_ROPE 128

// X Items
#define ITEM_X_ATTACK 129
#define ITEM_X_DEFENSE 130
#define ITEM_X_SP_ATK 131
#define ITEM_X_SP_DEF 132
#define ITEM_X_SPEED 133
#define ITEM_X_ACCURACY 134

#define ITEM_DIRE_HIT 135
#define ITEM_GUARD_SPEC 136

// Escape Items
#define ITEM_POKE_DOLL 137
#define ITEM_FLUFFY_TAIL 138
#define ITEM_POKE_TOY 139

#define ITEM_MAX_MUSHROOMS 140

// Treasures
#define ITEM_BOTTLE_CAP 141
#define ITEM_GOLD_BOTTLE_CAP 142
#define ITEM_NUGGET 143
#define ITEM_BIG_NUGGET 144
#define ITEM_GREEN_UFO 145
#define ITEM_RED_UFO 146
#define ITEM_BLUE_UFO 147
#define ITEM_PEARL 148
#define ITEM_BIG_PEARL 149
#define ITEM_PEARL_STRING 150
#define ITEM_STARDUST 151
#define ITEM_STAR_PIECE 152
#define ITEM_COMET_SHARD 153
#define ITEM_SHOAL_SALT 154
#define ITEM_SHOAL_SHELL 155
#define ITEM_RED_SHARD 156
#define ITEM_BLUE_SHARD 157
#define ITEM_YELLOW_SHARD 158
#define ITEM_GREEN_SHARD 159
#define ITEM_HEART_SCALE 160
#define ITEM_HONEY 161
#define ITEM_RARE_BONE 162
#define ITEM_ODD_KEYSTONE 163
#define ITEM_PRETTY_FEATHER 164
#define ITEM_RELIC_COPPER 165
#define ITEM_RELIC_SILVER 166
#define ITEM_RELIC_GOLD 167
#define ITEM_RELIC_VASE 168
#define ITEM_RELIC_BAND 169
#define ITEM_RELIC_STATUE 170
#define ITEM_RELIC_CROWN 171
#define ITEM_STRANGE_SOUVENIR 172
#define ITEM_BIG_BAMBOO_SHOOT 173
#define ITEM_TINY_BAMBOO_SHOOT 174
#define ITEM_GIMMIGHOUL_COIN 175

// Fossils
#define ITEM_HELIX_FOSSIL 176
#define ITEM_DOME_FOSSIL 177
#define ITEM_OLD_AMBER 178
#define ITEM_ROOT_FOSSIL 179
#define ITEM_CLAW_FOSSIL 180
#define ITEM_ARMOR_FOSSIL 181
#define ITEM_SKULL_FOSSIL 182

// Mulch
#define ITEM_GROWTH_MULCH 183
#define ITEM_DAMP_MULCH 184
#define ITEM_STABLE_MULCH 185
#define ITEM_GOOEY_MULCH 186
#define ITEM_RICH_MULCH 187
#define ITEM_SURPRISE_MULCH 188
#define ITEM_BOOST_MULCH 189
#define ITEM_AMAZE_MULCH 190

// Mail
#define ITEM_ORANGE_MAIL 191
#define ITEM_HARBOR_MAIL 192
#define ITEM_GLITTER_MAIL 193
#define ITEM_MECH_MAIL 194
#define ITEM_WOOD_MAIL 195
#define ITEM_WAVE_MAIL 196
#define ITEM_BEAD_MAIL 197
#define ITEM_SHADOW_MAIL 198
#define ITEM_TROPIC_MAIL 199
#define ITEM_DREAM_MAIL 200
#define ITEM_FAB_MAIL 201
#define ITEM_RETRO_MAIL 202

#define FIRST_MAIL_INDEX ITEM_ORANGE_MAIL

// Evolution Items
#define ITEM_POWER_HEART 203
#define ITEM_GUARD_HEART 204
#define ITEM_SWIFT_HEART 205
#define ITEM_TECH_HEART 206
#define ITEM_HELPER_HEART 207
#define ITEM_JUST_HEART 208
#define ITEM_CHROME_HEART 209
#define ITEM_SHINY_STONE 210
#define ITEM_DUSK_STONE 211
#define ITEM_DAWN_STONE 212
#define ITEM_UPGRADE 213
#define ITEM_DUBIOUS_DISC 214
#define ITEM_LINKING_CORD 215

#define ITEM_EVERSTONE 216

// Nectars
#define ITEM_RED_NECTAR 217
#define ITEM_YELLOW_NECTAR 218
#define ITEM_PINK_NECTAR 219
#define ITEM_PURPLE_NECTAR 220

// Plates
#define ITEM_FLAME_PLATE 221
#define ITEM_SPLASH_PLATE 222
#define ITEM_ZAP_PLATE 223
#define ITEM_MEADOW_PLATE 224
#define ITEM_ICICLE_PLATE 225
#define ITEM_FIST_PLATE 226
#define ITEM_TOXIC_PLATE 227
#define ITEM_EARTH_PLATE 228
#define ITEM_SKY_PLATE 229
#define ITEM_MIND_PLATE 230
#define ITEM_INSECT_PLATE 231
#define ITEM_STONE_PLATE 232
#define ITEM_SPOOKY_PLATE 233
#define ITEM_DRACO_PLATE 234
#define ITEM_DREAD_PLATE 235
#define ITEM_IRON_PLATE 236
#define ITEM_PIXIE_PLATE 237

// Colored Orbs
#define ITEM_RED_ORB 238
#define ITEM_BLUE_ORB 239

// Gems
#define ITEM_ILLUSION_CARD 240
#define ITEM_FIRE_CARD 241
#define ITEM_WATER_CARD 242
#define ITEM_WIND_CARD 243
#define ITEM_NATURE_CARD 244
#define ITEM_ICE_CARD 245
#define ITEM_DREAM_CARD 246
#define ITEM_MIASMA_CARD 247
#define ITEM_EARTH_CARD 248
#define ITEM_FLYING_GEM 249
#define ITEM_PSYCHIC_GEM 250
#define ITEM_BUG_GEM 251
#define ITEM_ROCK_GEM 252
#define ITEM_GHOST_GEM 253
#define ITEM_DRAGON_GEM 254
#define ITEM_DARK_GEM 255
#define ITEM_STEEL_GEM 256
#define ITEM_COSMIC_CARD 257

// Species-specific Held Items
#define ITEM_ICY_BALL 258
#define ITEM_ASSIST_BALL 259
#define ITEM_MUSIC_BALL 260
#define ITEM_GLOW_BALL 261
#define ITEM_DARK_BALL 262
#define ITEM_BLOOMERS 263
#define ITEM_DARK_RIBBON 264
#define ITEM_BIG_CLOUD 265
#define ITEM_KUSANAGI 266
#define ITEM_YATA_MIRROR 267
#define ITEM_DOUBLE_SOUL 268
#define ITEM_QUICK_POWDER 269

// Incenses
#define ITEM_SEA_INCENSE 270
#define ITEM_LAX_INCENSE 271
#define ITEM_ODD_INCENSE 272
#define ITEM_ROCK_INCENSE 273
#define ITEM_FULL_INCENSE 274
#define ITEM_WAVE_INCENSE 275
#define ITEM_ROSE_INCENSE 276
#define ITEM_LUCK_INCENSE 277
#define ITEM_PURE_INCENSE 278

// Contest Scarves
#define ITEM_RED_SCARF 279
#define ITEM_BLUE_SCARF 280
#define ITEM_PINK_SCARF 281
#define ITEM_GREEN_SCARF 282
#define ITEM_YELLOW_SCARF 283

// EV Gain Modifiers
#define ITEM_MACHO_BRACE 284
#define ITEM_POWER_WEIGHT 285
#define ITEM_POWER_BRACER 286
#define ITEM_POWER_BELT 287
#define ITEM_POWER_LENS 288
#define ITEM_POWER_BAND 289
#define ITEM_POWER_ANKLET 290

// Type-boosting Held Items
#define ITEM_BRIDAL_GOWN 291
#define ITEM_WEDDING_DRESS ITEM_BRIDAL_GOWN
#define ITEM_GOTHIC_DRESS 292
#define ITEM_GOTHIC_OUTFIT ITEM_GOTHIC_DRESS
#define ITEM_SWIMSUIT 293
#define ITEM_NINJA_SUIT 294
#define ITEM_NINJA_COSTUME ITEM_NINJA_SUIT
#define ITEM_CAMOUFLAGE 295
#define ITEM_THICK_FUR 296
#define ITEM_CHINESE_DRESS 297
#define ITEM_NURSE_UNIFORM 298
#define ITEM_GYM_SUIT 299
#define ITEM_SPORTS_SWEATER ITEM_GYM_SUIT
#define ITEM_STEWARDESS 300
#define ITEM_AIRLINE_UNIFORM ITEM_STEWARDESS
#define ITEM_WITCHS_ROBE 301
#define ITEM_WITCH_COSTUME ITEM_WITCHS_ROBE
#define ITEM_BLAZER 302
#define ITEM_BUNNY_SUIT 303
#define ITEM_BUNNY_COSTUME ITEM_BUNNY_SUIT
#define ITEM_BURIAL_DRESS 304
#define ITEM_PRIESTESS 305
#define ITEM_PRIEST_GARB ITEM_PRIESTESS
#define ITEM_BLACK_GLASSES 306
#define ITEM_MISTRESS_OUTFIT ITEM_BLACK_GLASSES
#define ITEM_MAID_UNIFORM 307
#define ITEM_FAIRY_FEATHER 308

// Alternate type-boosting items
#define ITEM_SHARP_SWORD 309
#define ITEM_DUBIOUS_TOME 310

// Tera Shards
#define ITEM_BUG_TERA_SHARD 311
#define ITEM_DARK_TERA_SHARD 312
#define ITEM_DRAGON_TERA_SHARD 313
#define ITEM_ELECTRIC_TERA_SHARD 314
#define ITEM_FAIRY_TERA_SHARD 315
#define ITEM_FIGHTING_TERA_SHARD 316
#define ITEM_FIRE_TERA_SHARD 317
#define ITEM_FLYING_TERA_SHARD 318
#define ITEM_GHOST_TERA_SHARD 319
#define ITEM_GRASS_TERA_SHARD 320
#define ITEM_GROUND_TERA_SHARD 321
#define ITEM_ICE_TERA_SHARD 322
#define ITEM_NORMAL_TERA_SHARD 323
#define ITEM_POISON_TERA_SHARD 324
#define ITEM_PSYCHIC_TERA_SHARD 325
#define ITEM_ROCK_TERA_SHARD 326
#define ITEM_STEEL_TERA_SHARD 327
#define ITEM_WATER_TERA_SHARD 328
#define ITEM_STELLAR_TERA_SHARD 329

// Choice Items
#define ITEM_CHOICE_BAND 330
#define ITEM_CHOICE_SPECS 331
#define ITEM_CHOICE_SCARF 332

// Status Orbs
#define ITEM_FLAME_ORB 333
#define ITEM_TOXIC_ORB 334
#define ITEM_FROST_ORB 335

// Weather Rocks
#define ITEM_DAMP_ROCK 336
#define ITEM_HEAT_ROCK 337
#define ITEM_SMOOTH_ROCK 338
#define ITEM_ICY_ROCK 339
#define ITEM_SCARLET_ROCK 340

// Terrain Seeds
#define ITEM_ELECTRIC_SEED 341
#define ITEM_PSYCHIC_SEED 342
#define ITEM_MISTY_SEED 343
#define ITEM_GRASSY_SEED 344

// Type-activated Stat Modifiers
#define ITEM_ABSORB_BULB 345
#define ITEM_CELL_BATTERY 346
#define ITEM_LUMINOUS_MOSS 347
#define ITEM_SNOWBALL 348

// Misc. Held Items
#define ITEM_BRIGHT_POWDER 349
#define ITEM_WHITE_HERB 350
#define ITEM_EXP_SHARE 351
#define ITEM_EXP_ALL ITEM_EXP_SHARE // Gen I name
#define ITEM_QUICK_CLAW 352
#define ITEM_SOOTHE_BELL 353
#define ITEM_MENTAL_HERB 354
#define ITEM_KINGS_ROCK 355
#define ITEM_DONATION_BOX 356
#define ITEM_CLEANSE_TAG 357
#define ITEM_SMOKE_BALL 358
#define ITEM_FOCUS_BAND 359
#define ITEM_LUCKY_EGG 360
#define ITEM_SCOPE_LENS 361
#define ITEM_BENTO_BOX 362
#define ITEM_SHELL_BELL 363
#define ITEM_WIDE_LENS 364
#define ITEM_MUSCLE_BAND 365
#define ITEM_WISE_GLASSES 366
#define ITEM_EXPERT_BELT 367
#define ITEM_LIGHT_CLAY 368
#define ITEM_LIFE_ORB 369
#define ITEM_POWER_HERB 370
#define ITEM_FOCUS_SASH 371
#define ITEM_ZOOM_LENS 372
#define ITEM_METRONOME 373
#define ITEM_IRON_BALL 374
#define ITEM_LAGGING_TAIL 375
#define ITEM_DESTINY_KNOT 376
#define ITEM_BLACK_SLUDGE 377
#define ITEM_GRIP_CLAW 378
#define ITEM_STICKY_BARB 379
#define ITEM_SHED_SHELL 380
#define ITEM_BIG_ROOT 381
#define ITEM_RAZOR_CLAW 382
#define ITEM_RAZOR_FANG 383
#define ITEM_EVIOLITE 384
#define ITEM_FLOAT_STONE 385
#define ITEM_ROCKY_HELMET 386
#define ITEM_AIR_BALLOON 387
#define ITEM_RED_CARD 388
#define ITEM_RING_TARGET 389
#define ITEM_BINDING_BAND 390
#define ITEM_EJECT_BUTTON 391
#define ITEM_WEAKNESS_POLICY 392
#define ITEM_ASSAULT_VEST 393
#define ITEM_SAFETY_GOGGLES 394
#define ITEM_ADRENALINE_ORB 395
#define ITEM_TERRAIN_EXTENDER 396
#define ITEM_PROTECTIVE_PADS 397
#define ITEM_THROAT_SPRAY 398
#define ITEM_EJECT_PACK 399
#define ITEM_HEAVY_DUTY_BOOTS 400
#define ITEM_BLUNDER_POLICY 401
#define ITEM_ROOM_SERVICE 402
#define ITEM_UTILITY_UMBRELLA 403
#define ITEM_ABILITY_SHIELD 404
#define ITEM_CLEAR_AMULET 405
#define ITEM_PUNCHING_GLOVE 406
#define ITEM_COVERT_CLOAK 407
#define ITEM_LOADED_DICE 408
#define ITEM_BOOSTER_ENERGY 409
#define ITEM_MIRROR_HERB 410
#define ITEM_BERSERK_GENE 411

// Berries
#if B_CONFUSE_BERRIES_HEAL >= GEN_8
    #define CONFUSE_BERRY_HEAL_FRACTION 3
#elif B_CONFUSE_BERRIES_HEAL == GEN_7
    #define CONFUSE_BERRY_HEAL_FRACTION 2
#else
    #define CONFUSE_BERRY_HEAL_FRACTION 8
#endif

#define CONFUSE_BERRY_HP_FRACTION ((B_CONFUSE_BERRIES_HEAL >= GEN_7) ? 4 : 2)

#define ITEM_CHERI_BERRY 412
#define ITEM_CHESTO_BERRY 413
#define ITEM_PECHA_BERRY 414
#define ITEM_RAWST_BERRY 415
#define ITEM_ASPEAR_BERRY 416
#define ITEM_LEPPA_BERRY 417
#define ITEM_ORAN_BERRY 418
#define ITEM_PERSIM_BERRY 419
#define ITEM_LUM_BERRY 420
#define ITEM_SITRUS_BERRY 421
#define ITEM_FIGY_BERRY 422
#define ITEM_WIKI_BERRY 423
#define ITEM_MAGO_BERRY 424
#define ITEM_AGUAV_BERRY 425
#define ITEM_IAPAPA_BERRY 426
#define ITEM_RAZZ_BERRY 427
#define ITEM_BLUK_BERRY 428
#define ITEM_NANAB_BERRY 429
#define ITEM_WEPEAR_BERRY 430
#define ITEM_PINAP_BERRY 431
#define ITEM_POMEG_BERRY 432
#define ITEM_KELPSY_BERRY 433
#define ITEM_QUALOT_BERRY 434
#define ITEM_HONDEW_BERRY 435
#define ITEM_GREPA_BERRY 436
#define ITEM_TAMATO_BERRY 437
#define ITEM_CORNN_BERRY 438
#define ITEM_MAGOST_BERRY 439
#define ITEM_RABUTA_BERRY 440
#define ITEM_NOMEL_BERRY 441
#define ITEM_SPELON_BERRY 442
#define ITEM_PAMTRE_BERRY 443
#define ITEM_WATMEL_BERRY 444
#define ITEM_DURIN_BERRY 445
#define ITEM_BELUE_BERRY 446
#define ITEM_CHILAN_BERRY 447
#define ITEM_OCCA_BERRY 448
#define ITEM_PASSHO_BERRY 449
#define ITEM_WACAN_BERRY 450
#define ITEM_RINDO_BERRY 451
#define ITEM_YACHE_BERRY 452
#define ITEM_CHOPLE_BERRY 453
#define ITEM_KEBIA_BERRY 454
#define ITEM_SHUCA_BERRY 455
#define ITEM_COBA_BERRY 456
#define ITEM_PAYAPA_BERRY 457
#define ITEM_TANGA_BERRY 458
#define ITEM_CHARTI_BERRY 459
#define ITEM_KASIB_BERRY 460
#define ITEM_HABAN_BERRY 461
#define ITEM_COLBUR_BERRY 462
#define ITEM_BABIRI_BERRY 463
#define ITEM_ROSELI_BERRY 464
#define ITEM_LIECHI_BERRY 465
#define ITEM_GANLON_BERRY 466
#define ITEM_SALAC_BERRY 467
#define ITEM_PETAYA_BERRY 468
#define ITEM_APICOT_BERRY 469
#define ITEM_LANSAT_BERRY 470
#define ITEM_STARF_BERRY 471
#define ITEM_ENIGMA_BERRY 472
#define ITEM_MICLE_BERRY 473
#define ITEM_CUSTAP_BERRY 474
#define ITEM_JABOCA_BERRY 475
#define ITEM_ROWAP_BERRY 476
#define ITEM_KEE_BERRY 477
#define ITEM_MARANGA_BERRY 478

#define ITEM_PUMKIN_BERRY 479
#define ITEM_DRASH_BERRY 480
#define ITEM_EGGANT_BERRY 481
#define ITEM_STRIB_BERRY 482
#define ITEM_TURLAN_BERRY 483
#define ITEM_NUTPEA_BERRY 484
#define ITEM_IONNO_BERRY 485
#define ITEM_KUO_BERRY 486
#define ITEM_YAGO_BERRY 487
#define ITEM_TOUGA_BERRY 488
#define ITEM_GARLIG_BERRY 489
#define ITEM_TOPO_BERRY 490

#define FIRST_BERRY_INDEX ITEM_CHERI_BERRY
#define LAST_BERRY_INDEX  ITEM_TOPO_BERRY

// TMs/HMs
#define ITEM_TM01 491
#define ITEM_TM02 492
#define ITEM_TM03 493
#define ITEM_TM04 494
#define ITEM_TM05 495
#define ITEM_TM06 496
#define ITEM_TM07 497
#define ITEM_TM08 498
#define ITEM_TM09 499
#define ITEM_TM10 500
#define ITEM_TM11 501
#define ITEM_TM12 502
#define ITEM_TM13 503
#define ITEM_TM14 504
#define ITEM_TM15 505
#define ITEM_TM16 506
#define ITEM_TM17 507
#define ITEM_TM18 508
#define ITEM_TM19 509
#define ITEM_TM20 510
#define ITEM_TM21 511
#define ITEM_TM22 512
#define ITEM_TM23 513
#define ITEM_TM24 514
#define ITEM_TM25 515
#define ITEM_TM26 516
#define ITEM_TM27 517
#define ITEM_TM28 518
#define ITEM_TM29 519
#define ITEM_TM30 520
#define ITEM_TM31 521
#define ITEM_TM32 522
#define ITEM_TM33 523
#define ITEM_TM34 524
#define ITEM_TM35 525
#define ITEM_TM36 526
#define ITEM_TM37 527
#define ITEM_TM38 528
#define ITEM_TM39 529
#define ITEM_TM40 530
#define ITEM_TM41 531
#define ITEM_TM42 532
#define ITEM_TM43 533
#define ITEM_TM44 534
#define ITEM_TM45 535
#define ITEM_TM46 536
#define ITEM_TM47 537
#define ITEM_TM48 538
#define ITEM_TM49 539
#define ITEM_TM50 540
#define ITEM_TM51 541
#define ITEM_TM52 542
#define ITEM_TM53 543
#define ITEM_TM54 544
#define ITEM_TM55 545
#define ITEM_TM56 546
#define ITEM_TM57 547
#define ITEM_TM58 548
#define ITEM_TM59 549
#define ITEM_TM60 550
#define ITEM_TM61 551
#define ITEM_TM62 552
#define ITEM_TM63 553
#define ITEM_TM64 554
#define ITEM_TM65 555
#define ITEM_TM66 556
#define ITEM_TM67 557
#define ITEM_TM68 558
#define ITEM_TM69 559
#define ITEM_TM70 560
#define ITEM_TM71 561
#define ITEM_TM72 562
#define ITEM_TM73 563
#define ITEM_TM74 564
#define ITEM_TM75 565
#define ITEM_TM76 566
#define ITEM_TM77 567
#define ITEM_TM78 568
#define ITEM_TM79 569
#define ITEM_TM80 570
#define ITEM_TM81 571
#define ITEM_TM82 572
#define ITEM_TM83 573
#define ITEM_TM84 574
#define ITEM_TM85 575
#define ITEM_TM86 576
#define ITEM_TM87 577
#define ITEM_TM88 578
#define ITEM_TM89 579
#define ITEM_TM90 580
#define ITEM_TM91 581
#define ITEM_TM92 582
#define ITEM_TM93 583
#define ITEM_TM94 584
#define ITEM_TM95 585
#define ITEM_TM96 586
#define ITEM_TM97 587
#define ITEM_TM98 588
#define ITEM_TM99 589
#define ITEM_TM100 590

#define ITEM_HM01 591
#define ITEM_HM02 592
#define ITEM_HM03 593
#define ITEM_HM04 594
#define ITEM_HM05 595
#define ITEM_HM06 596
#define ITEM_HM07 597
#define ITEM_HM08 598

// Charms
#define ITEM_OVAL_CHARM 599
#define ITEM_SHINY_CHARM 600
#define ITEM_CATCHING_CHARM 601
#define ITEM_EXP_CHARM 602
#define ITEM_GLIMMERING_CHARM 603

// Battle Mechanic Key Items
#define ITEM_MEGA_RING 604
#define ITEM_Z_POWER_RING 605
#define ITEM_DYNAMAX_BAND 606
#define ITEM_TERA_ORB 607

// Misc. Key Items
#define ITEM_BICYCLE 608
#define ITEM_MACH_BIKE 609
#define ITEM_ACRO_BIKE 610
#define ITEM_FISHING_ROD 611
#define ITEM_OLD_ROD 612
#define ITEM_GOOD_ROD 613
#define ITEM_SUPER_ROD 614
#define ITEM_DOWSING_MACHINE 615
#define ITEM_ITEMFINDER ITEM_DOWSING_MACHINE // Pre-Gen IV name
#define ITEM_DOWSING_MCHN ITEM_DOWSING_MACHINE // Gen IV-V name
#define ITEM_TOWN_MAP 616
#define ITEM_VS_SEEKER 617
#define ITEM_TM_CASE 618
#define ITEM_BERRY_POUCH 619
#define ITEM_POKEMON_BOX_LINK 620
#define ITEM_POKEMON_BOX ITEM_POKEMON_BOX_LINK // Pre-Gen VIII name
#define ITEM_COIN_CASE 621
#define ITEM_POWDER_JAR 622
#define ITEM_WAILMER_PAIL 623
#define ITEM_POKE_RADAR 624
#define ITEM_POKEBLOCK_CASE 625
#define ITEM_SOOT_SACK 626
#define ITEM_POKE_FLUTE 627
#define ITEM_FAME_CHECKER 628
#define ITEM_TEACHY_TV 629
#define ITEM_TOHOVIAL 630
#define ITEM_HEXORB 631
#define ITEM_OUTFIT_BOX 632
#define ITEM_MUSIC_PLAYER 633

// HM Items
#define ITEM_BIG_AXE 634
#define ITEM_PAGER 635
#define ITEM_SURFBOARD 636
#define ITEM_POWER_GLOVE 637
#define ITEM_LANTERN 638
#define ITEM_PICKAXE 639
#define ITEM_CLIMBING_GEAR 640
#define ITEM_SCUBA_GEAR 641

// Story Key Items
#define ITEM_SS_TICKET 642
#define ITEM_EON_TICKET 643
#define ITEM_MYSTIC_TICKET 644
#define ITEM_AURORA_TICKET 645
#define ITEM_OLD_SEA_MAP 647
#define ITEM_LETTER 648
#define ITEM_DEVON_PARTS 649
#define ITEM_DEVON_GOODS ITEM_DEVON_PARTS // Pre-Gen VI name
#define ITEM_GO_GOGGLES 650
#define ITEM_DEVON_SCOPE 651
#define ITEM_BASEMENT_KEY 652
#define ITEM_SCANNER 653
#define ITEM_STORAGE_KEY 654
#define ITEM_KEY_TO_ROOM_1 655
#define ITEM_RM_1_KEY ITEM_KEY_TO_ROOM_1 // Pre-Gen VI name
#define ITEM_KEY_TO_ROOM_2 656
#define ITEM_RM_2_KEY ITEM_KEY_TO_ROOM_2 // Pre-Gen VI name
#define ITEM_KEY_TO_ROOM_4 657
#define ITEM_RM_4_KEY ITEM_KEY_TO_ROOM_4 // Pre-Gen VI name
#define ITEM_KEY_TO_ROOM_6 658
#define ITEM_RM_6_KEY ITEM_KEY_TO_ROOM_6 // Pre-Gen VI name
#define ITEM_METEORITE 659
#define ITEM_MAGMA_EMBLEM 660
#define ITEM_CONTEST_PASS 661
#define ITEM_PARCEL 662
#define ITEM_OAKS_PARCEL ITEM_PARCEL // Pre-Gen IV name
#define ITEM_SECRET_KEY 663
#define ITEM_BIKE_VOUCHER 664
#define ITEM_GOLD_TEETH 665
#define ITEM_CARD_KEY 666
#define ITEM_LIFT_KEY 667
#define ITEM_SILPH_SCOPE 668
#define ITEM_TRI_PASS 669
#define ITEM_RAINBOW_PASS 670
#define ITEM_TEA 671
#define ITEM_RUBY 672
#define ITEM_SAPPHIRE 673

// Form-changing Key Items
#define ITEM_ROTOM_CATALOG 674
#define ITEM_GRACIDEA 675
#define ITEM_REVEAL_GLASS 676
#define ITEM_DNA_SPLICERS 677
#define ITEM_ZYGARDE_CUBE 678
#define ITEM_PRISON_BOTTLE 679
#define ITEM_N_SOLARIZER 680
#define ITEM_N_LUNARIZER 681
#define ITEM_REINS_OF_UNITY 682

// GEN IX ITEMS
#define ITEM_SCROLL_OF_DARKNESS 683
#define ITEM_SCROLL_OF_WATERS 684

#define ITEM_JUBILIFE_MUFFIN 685
#define ITEM_REMEDY 686
#define ITEM_FINE_REMEDY 687
#define ITEM_SUPERB_REMEDY 688
#define ITEM_AUX_EVASION 689
#define ITEM_AUX_GUARD 690
#define ITEM_AUX_POWER 691
#define ITEM_AUX_POWERGUARD 692
#define ITEM_CHOICE_DUMPLING 693
#define ITEM_SWAP_SNACK 694
#define ITEM_TWICE_SPICED_RADISH 695
#define ITEM_POKESHI_DOLL 696

// Mega Stones
#define ITEM_VENUSAURITE 697
#define ITEM_CHARIZARDITE_X 698
#define ITEM_CHARIZARDITE_Y 699
#define ITEM_BLASTOISINITE 700
#define ITEM_BEEDRILLITE 701
#define ITEM_PIDGEOTITE 702
#define ITEM_ALAKAZITE 703
#define ITEM_SLOWBRONITE 704
#define ITEM_GENGARITE 705
#define ITEM_KANGASKHANITE 706
#define ITEM_PINSIRITE 707
#define ITEM_GYARADOSITE 708
#define ITEM_AERODACTYLITE 709
#define ITEM_MEWTWONITE_X 710
#define ITEM_MEWTWONITE_Y 711
#define ITEM_AMPHAROSITE 712
#define ITEM_STEELIXITE 713
#define ITEM_SCIZORITE 714
#define ITEM_HERACRONITE 715
#define ITEM_HOUNDOOMINITE 716
#define ITEM_TYRANITARITE 717
#define ITEM_SCEPTILITE 718
#define ITEM_BLAZIKENITE 719
#define ITEM_SWAMPERTITE 720
#define ITEM_GARDEVOIRITE 721
#define ITEM_SABLENITE 722
#define ITEM_MAWILITE 723
#define ITEM_AGGRONITE 724
#define ITEM_MEDICHAMITE 725
#define ITEM_MANECTITE 726
#define ITEM_SHARPEDONITE 727
#define ITEM_CAMERUPTITE 728
#define ITEM_ALTARIANITE 729
#define ITEM_BANETTITE 730
#define ITEM_ABSOLITE 731
#define ITEM_GLALITITE 732
#define ITEM_SALAMENCITE 733
#define ITEM_METAGROSSITE 734
#define ITEM_LATIASITE 735
#define ITEM_LATIOSITE 736
#define ITEM_LOPUNNITE 737
#define ITEM_GARCHOMPITE 738
#define ITEM_LUCARIONITE 739
#define ITEM_ABOMASITE 740
#define ITEM_GALLADITE 741
#define ITEM_AUDINITE 742
#define ITEM_DIANCITE 743

// Z-Crystals
#define ITEM_NORMALIUM_Z 744
#define ITEM_FIRIUM_Z 745
#define ITEM_WATERIUM_Z 746
#define ITEM_ELECTRIUM_Z 747
#define ITEM_GRASSIUM_Z 748
#define ITEM_ICIUM_Z 749
#define ITEM_FIGHTINIUM_Z 750
#define ITEM_POISONIUM_Z 751
#define ITEM_GROUNDIUM_Z 752
#define ITEM_FLYINIUM_Z 753
#define ITEM_PSYCHIUM_Z 754
#define ITEM_BUGINIUM_Z 755
#define ITEM_ROCKIUM_Z 756
#define ITEM_GHOSTIUM_Z 757
#define ITEM_DRAGONIUM_Z 758
#define ITEM_DARKINIUM_Z 759
#define ITEM_STEELIUM_Z 760
#define ITEM_FAIRIUM_Z 761
#define ITEM_INCINIUM_Z 762
#define ITEM_ULTRANECROZIUM_Z 763

// Drives
#define ITEM_DOUSE_DRIVE 764
#define ITEM_SHOCK_DRIVE 765
#define ITEM_BURN_DRIVE 766
#define ITEM_CHILL_DRIVE 767

// Memories
#define ITEM_FIRE_MEMORY 768
#define ITEM_WATER_MEMORY 769
#define ITEM_ELECTRIC_MEMORY 770
#define ITEM_GRASS_MEMORY 771
#define ITEM_ICE_MEMORY 772
#define ITEM_FIGHTING_MEMORY 773
#define ITEM_POISON_MEMORY 774
#define ITEM_GROUND_MEMORY 775
#define ITEM_FLYING_MEMORY 776
#define ITEM_PSYCHIC_MEMORY 777
#define ITEM_BUG_MEMORY 778
#define ITEM_ROCK_MEMORY 779
#define ITEM_GHOST_MEMORY 780
#define ITEM_DRAGON_MEMORY 781
#define ITEM_DARK_MEMORY 782
#define ITEM_STEEL_MEMORY 783
#define ITEM_FAIRY_MEMORY 784

#define ITEM_RUSTED_SWORD 785
#define ITEM_RUSTED_SHIELD 786

#define ITEM_ADAMANT_CRYSTAL 787
#define ITEM_GRISEOUS_CORE 788
#define ITEM_LUSTROUS_GLOBE 789
#define ITEM_CORNERSTONE_MASK 790
#define ITEM_WELLSPRING_MASK 791
#define ITEM_HEARTHFLAME_MASK 792

// HOPO BERRY
// LEGEND PLATE

#define ITEMS_COUNT 793
#define ITEM_FIELD_ARROW ITEMS_COUNT

// A special item id associated with "Cancel"/"Exit" etc. in a list of items or decorations
// Its icon is defined at ITEMS_COUNT as the "return to field" arrow
#define ITEM_LIST_END 0xFFFF

// Range of berries given out by various NPCS
#define FIRST_BERRY_MASTER_BERRY      ITEM_POMEG_BERRY
#define LAST_BERRY_MASTER_BERRY       ITEM_NOMEL_BERRY
#define FIRST_BERRY_MASTER_WIFE_BERRY ITEM_CHERI_BERRY
#define LAST_BERRY_MASTER_WIFE_BERRY  ITEM_SITRUS_BERRY
#define FIRST_KIRI_BERRY              ITEM_POMEG_BERRY
#define LAST_KIRI_BERRY               ITEM_NOMEL_BERRY
#define FIRST_ROUTE_114_MAN_BERRY     ITEM_RAZZ_BERRY
#define LAST_ROUTE_114_MAN_BERRY      ITEM_PINAP_BERRY

#define NUM_BERRY_MASTER_BERRIES          (LAST_BERRY_MASTER_BERRY - FIRST_BERRY_MASTER_BERRY + 1)
#define NUM_BERRY_MASTER_BERRIES_SKIPPED  (FIRST_BERRY_MASTER_BERRY - FIRST_BERRY_INDEX)
#define NUM_BERRY_MASTER_WIFE_BERRIES     (LAST_BERRY_MASTER_WIFE_BERRY - FIRST_BERRY_MASTER_WIFE_BERRY + 1)
#define NUM_KIRI_BERRIES                  (LAST_KIRI_BERRY - FIRST_KIRI_BERRY + 1)
#define NUM_KIRI_BERRIES_SKIPPED          (FIRST_KIRI_BERRY - FIRST_BERRY_INDEX)
#define NUM_ROUTE_114_MAN_BERRIES         (LAST_ROUTE_114_MAN_BERRY - FIRST_ROUTE_114_MAN_BERRY + 1)
#define NUM_ROUTE_114_MAN_BERRIES_SKIPPED (FIRST_ROUTE_114_MAN_BERRY - FIRST_BERRY_INDEX)

#define ITEM_TO_BERRY(itemId) (((itemId) - FIRST_BERRY_INDEX) + 1)
#define ITEM_TO_MAIL(itemId) ((itemId) - FIRST_MAIL_INDEX)
#define MAIL_NONE 0xFF
#define ITEM_TO_MULCH(itemId)(((itemId) - ITEM_GROWTH_MULCH) + 1)

#define NUM_TECHNICAL_MACHINES 100
#define NUM_HIDDEN_MACHINES 8

#define MAX_BAG_ITEM_CAPACITY         999
#define MAX_PC_ITEM_CAPACITY          999
#define MAX_PYRAMID_BAG_ITEM_CAPACITY  99 // Values higher than 255 require free SaveBlock2 space.

#define MAX_ITEM_DIGITS         ((MAX_BAG_ITEM_CAPACITY > 99) ? 3 : 2)
#define MAX_PYRAMID_ITEM_DIGITS ((MAX_PYRAMID_BAG_ITEM_CAPACITY > 99) ? 3 : 2)

// Secondary IDs for rods
#define OLD_ROD   0
#define GOOD_ROD  1
#define SUPER_ROD 2

// Secondary IDs for bikes
#define MACH_BIKE 0
#define ACRO_BIKE 1

// Item parameters for EXP Candies
#define EXP_100   1
#define EXP_800   2
#define EXP_3000  3
#define EXP_10000 4
#define EXP_30000 5

// Item type IDs (used to determine the exit callback)
#define ITEM_USE_MAIL             0
#define ITEM_USE_PARTY_MENU       1
#define ITEM_USE_FIELD            2
#define ITEM_USE_PBLOCK_CASE      3
#define ITEM_USE_BAG_MENU         4 // No exit callback, stays in bag menu
#define ITEM_USE_PARTY_MENU_MOVES 5

// Item battle script IDs (need to be non-zero)
#define EFFECT_ITEM_RESTORE_HP              1
#define EFFECT_ITEM_CURE_STATUS             2
#define EFFECT_ITEM_HEAL_AND_CURE_STATUS    3
#define EFFECT_ITEM_INCREASE_STAT           4
#define EFFECT_ITEM_SET_MIST                5
#define EFFECT_ITEM_SET_FOCUS_ENERGY        6
#define EFFECT_ITEM_ESCAPE                  7
#define EFFECT_ITEM_THROW_BALL              8
#define EFFECT_ITEM_REVIVE                  9
#define EFFECT_ITEM_RESTORE_PP              10
#define EFFECT_ITEM_INCREASE_ALL_STATS      11
#define EFFECT_ITEM_USE_POKE_FLUTE          12
#define EFFECT_ITEM_TAKE_DAMAGE             13

// Enigma Berry dummy constant
#define EFFECT_ITEM_ENIGMA_BERRY_EREADER    1

#endif  // GUARD_CONSTANTS_ITEMS_H
