#ifndef GUARD_CONSTANTS_MUSIC_PLAYER_H
#define GUARD_CONSTANTS_MUSIC_PLAYER_H

enum MP3PlayerTracks
{
    MUSIC_TRACK_ZGS_VS_WILD,
    MUSIC_TRACK_ZGS_VS_TRAINER,
    MUSIC_TRACK_ZGS_VS_CHAMPION,
    MUSIC_TRACK_ZGS_VICTORY_WILD,
    MUSIC_TRACK_ZGS_VICTORY_TRAINER,
    MUSIC_TRACK_COUNT,
};

enum MP3Menus
{
    MP3_MENU_MAIN,
    MP3_MENU_PLAY_MUSIC,
    MP3_MENU_PLAYLISTS,
    MP3_MENU_RESET_ALL,
    MP3_MENU_COUNT,
};

enum MP3MenuMain
{
    MP3_MAIN_PLAY_MUSIC,
    MP3_MAIN_PLAYLISTS,
    MP3_MAIN_MUSIC_OVERRIDES,
    MP3_MAIN_OVERRIDE_SETTINGS,
    MP3_MAIN_RESET_ALL,
    MP3_MAIN_PUT_AWAY,
    MP3_MAIN_COUNT,
};

enum MP3Background
{
    MP3_BG_1,
    MP3_BG_2,
    MP3_BG_3,
};

enum MP3WindowIds
{
    MP3_WINDOW_HEADER,
    MP3_WINDOW_DESCRIPTION,
    MP3_WINDOW_LIST,
};

#endif // GUARD_CONSTANTS_MUSIC_PLAYER_H
