#ifndef GUARD_CONSTANTS_SPEAKER_NAMES_H
#define GUARD_CONSTANTS_SPEAKER_NAMES_H

enum SpeakerNames {
    SP_NAME_NONE = 0,
    SP_NAME_MOM,
    SP_NAME_PLAYER,
    SP_NAME_GRUNT,
    SP_NAME_NURSE,
    SP_NAME_UFO_TRADER,
    SP_NAME_AMELIA,
    SP_NAME_GURA,
    SP_NAME_INA,
    SP_NAME_CALLI,
    SP_NAME_KIARA,
    SP_NAME_MUMEI,
    SP_NAME_FAUNA,
    SP_NAME_KRONII,
    SP_NAME_BAELZ,
    SP_NAME_SANA,
    SP_NAME_IRYS,
    SP_NAME_SHIORI,
    SP_NAME_NERISSA,
    SP_NAME_BIJOU,
    SP_NAME_FUWAWA,
    SP_NAME_MOCOCO,
    SP_NAME_GIGI,
    SP_NAME_CECILIA,
    SP_NAME_RAORA,
    SP_NAME_ELIZABETH,
    SP_NAME_MOKOU,
    SP_NAME_DOISE,
    SP_NAME_LANCER,
    SP_NAME_AXIS,
    SP_NAME_COUNT
};

#endif // GUARD_CONSTANTS_SPEAKER_NAMES_H
