ApartmentLikeCarpet_MapScripts::
	.byte 0


ApartmentLikeCarpet_Script_Kronii::
# 4 "data/maps/ApartmentLikeCarpet/scripts.pory"
	lock
# 5 "data/maps/ApartmentLikeCarpet/scripts.pory"
	setspeakername gText_Kronii
# 6 "data/maps/ApartmentLikeCarpet/scripts.pory"
	msgbox ApartmentLikeCarpet_Text_KroniiNice
# 7 "data/maps/ApartmentLikeCarpet/scripts.pory"
	setspeakername gText_Gigi
# 8 "data/maps/ApartmentLikeCarpet/scripts.pory"
	msgbox ApartmentLikeCarpet_Text_GigiYeah
# 9 "data/maps/ApartmentLikeCarpet/scripts.pory"
	closemessage
# 10 "data/maps/ApartmentLikeCarpet/scripts.pory"
	delay 240
# 11 "data/maps/ApartmentLikeCarpet/scripts.pory"
	setspeakername gText_Kronii
# 12 "data/maps/ApartmentLikeCarpet/scripts.pory"
	msgbox ApartmentLikeCarpet_Text_Kronii2
# 13 "data/maps/ApartmentLikeCarpet/scripts.pory"
	setspeakername gText_Gigi
# 14 "data/maps/ApartmentLikeCarpet/scripts.pory"
	msgbox ApartmentLikeCarpet_Text_Gigi2
# 15 "data/maps/ApartmentLikeCarpet/scripts.pory"
	closemessage
# 16 "data/maps/ApartmentLikeCarpet/scripts.pory"
	delay 240
# 17 "data/maps/ApartmentLikeCarpet/scripts.pory"
	setspeakername gText_Kronii
# 18 "data/maps/ApartmentLikeCarpet/scripts.pory"
	msgbox ApartmentLikeCarpet_Text_Kronii3
# 19 "data/maps/ApartmentLikeCarpet/scripts.pory"
	setspeakername gText_Gigi
# 20 "data/maps/ApartmentLikeCarpet/scripts.pory"
	msgbox ApartmentLikeCarpet_Text_Gigi3
# 21 "data/maps/ApartmentLikeCarpet/scripts.pory"
	closemessage
# 22 "data/maps/ApartmentLikeCarpet/scripts.pory"
	delay 240
# 23 "data/maps/ApartmentLikeCarpet/scripts.pory"
	setspeakername gText_Kronii
# 24 "data/maps/ApartmentLikeCarpet/scripts.pory"
	msgbox ApartmentLikeCarpet_Text_Kronii4
# 25 "data/maps/ApartmentLikeCarpet/scripts.pory"
	setspeakername gText_Gigi
# 26 "data/maps/ApartmentLikeCarpet/scripts.pory"
	msgbox ApartmentLikeCarpet_Text_Gigi4
# 27 "data/maps/ApartmentLikeCarpet/scripts.pory"
	closemessage
# 28 "data/maps/ApartmentLikeCarpet/scripts.pory"
	delay 240
# 29 "data/maps/ApartmentLikeCarpet/scripts.pory"
	setspeakername gText_Kronii
# 30 "data/maps/ApartmentLikeCarpet/scripts.pory"
	msgbox ApartmentLikeCarpet_Text_Kronii5
# 31 "data/maps/ApartmentLikeCarpet/scripts.pory"
	release
	end


ApartmentLikeCarpet_Text_KroniiNice::
# 35 "data/maps/ApartmentLikeCarpet/scripts.pory"
	.string "It's nice, isn't it, Gigi?$"

ApartmentLikeCarpet_Text_GigiYeah::
# 39 "data/maps/ApartmentLikeCarpet/scripts.pory"
	.string "Yeah, I guess it is.$"

ApartmentLikeCarpet_Text_Kronii2::
# 43 "data/maps/ApartmentLikeCarpet/scripts.pory"
	.string "You know, I may be a bit of a pessimist\n"
	.string "myself, but I do feel like despite\l"
	.string "what's happening, things will be all good\l"
	.string "in the end.$"

ApartmentLikeCarpet_Text_Gigi2::
# 47 "data/maps/ApartmentLikeCarpet/scripts.pory"
	.string "You think so?$"

ApartmentLikeCarpet_Text_Kronii3::
# 51 "data/maps/ApartmentLikeCarpet/scripts.pory"
	.string "Yeah, I mean, yeah sure, there's some\n"
	.string "people around us that aren't gonna\l"
	.string "stick with us for long, but I know I\l"
	.string "can't stop it if they'll be happier with\l"
	.string "their new paths.$"

ApartmentLikeCarpet_Text_Gigi3::
# 55 "data/maps/ApartmentLikeCarpet/scripts.pory"
	.string "That seems fair, yeah.$"

ApartmentLikeCarpet_Text_Kronii4::
# 59 "data/maps/ApartmentLikeCarpet/scripts.pory"
	.string "You're pretty nice, Gigi. I may not\n"
	.string "always get along with you here, but\l"
	.string "you've always seen the best out of\l"
	.string "these situations here, even if they're\l"
	.string "not quite the most optimal.$"

ApartmentLikeCarpet_Text_Gigi4::
# 63 "data/maps/ApartmentLikeCarpet/scripts.pory"
	.string "Yeah.\p"
	.string "I mean, you are pretty cool yourself,\n"
	.string "putting aside your beauty and all.\p"
	.string "...\p"
	.string "She'll be happier, and I hope you'll be\n"
	.string "happy as well.$"

ApartmentLikeCarpet_Text_Kronii5::
# 67 "data/maps/ApartmentLikeCarpet/scripts.pory"
	.string "Thank you, Gigi.$"
